import React, { useState, useEffect } from 'react';
import { NativeDialog } from '../../../../shared/components/common/NativeDialog';
export function ReassignDayRouteModal({isOpen,onClose,cellData,onSave}) {
  const [ids,setIds] = useState([]);
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState('');
  useEffect(()=>{setIds(cellData?.currentData?.outletIds || []);setError('');},[cellData]);
  const move = (index,offset)=>setIds(previous=>{const next=[...previous];[next[index],next[index+offset]]=[next[index+offset],next[index]];return next;});
  const submit = async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave({salesId:cellData.salesId,day:cellData.day,outletIds:ids});}catch(err){setError(err.message);}finally{setBusy(false);}};
  return <NativeDialog open={isOpen && Boolean(cellData)} title={`3. Jadwal ${cellData?.day || ''}`} busy={busy} onClose={onClose}>{cellData && <form className="app-form" onSubmit={submit}><p>Pilih toko dari wilayah tim, lalu atur urutannya. Jadwal kosong berarti tanpa kunjungan. PJP yang sudah terbentuk tidak diubah.</p><label className="app-field">Tambah toko<select value="" disabled={busy} onChange={e=>{if(e.target.value)setIds(prev=>[...prev,e.target.value]);}}><option value="">Pilih toko…</option>{cellData.outlets.filter(o=>!ids.includes(o.id)).map(o=><option key={o.id} value={o.id}>{o.name} — {o.cluster?.name || ''}</option>)}</select></label><ol className="workspace-route-list">{ids.map((id,i)=><li className="workspace-card" key={id}><div><h3>{i+1}. {cellData.outlets.find(o=>o.id===id)?.name || 'Outlet tidak tersedia; hapus dari jadwal'}</h3><div className="app-actions"><button type="button" className="app-button" aria-label={`Naikkan toko urutan ${i+1}`} disabled={busy || i===0} onClick={()=>move(i,-1)}>Naik</button><button type="button" className="app-button" aria-label={`Turunkan toko urutan ${i+1}`} disabled={busy || i===ids.length-1} onClick={()=>move(i,1)}>Turun</button><button type="button" className="app-button" disabled={busy} onClick={()=>setIds(prev=>prev.filter(x=>x!==id))}>Hapus</button></div></div></li>)}</ol><p>{ids.length} toko terencana</p>{error && <p className="app-error" role="alert">{error}</p>}<div className="app-actions"><button type="button" className="app-button" disabled={busy} onClick={onClose}>Batal</button><button className="app-button app-button-primary" disabled={busy}>{busy?'Menyimpan…':'Simpan jadwal'}</button></div></form>}</NativeDialog>;
}
