/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#F4F7F6',
        surface: '#FFFFFF',
        'surface-dim': '#E0E3E2',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F4F7F6',
        'surface-container': '#EBEFED',
        'surface-container-high': '#E0E3E2',
        'surface-container-highest': '#D7DBDA',
        'on-surface': '#0F0F0F',
        'on-surface-variant': '#444748',
        'inverse-surface': '#0F0F0F',
        'inverse-on-surface': '#F4F7F6',
        primary: '#0F0F0F',
        'on-primary': '#FFFFFF',
        'primary-container': '#1C1B1B',
        'on-primary-container': '#858383',
        secondary: '#CCFF00',
        'on-secondary': '#0F0F0F',
        'secondary-container': '#CCFF00',
        'on-secondary-container': '#0F0F0F',
        'secondary-fixed': '#CCFF00',
        'secondary-fixed-dim': '#B3E600',
        tertiary: '#0066FF',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#E5F0FF',
        'on-tertiary-container': '#0066FF',
        error: '#D32F2F',
        'on-error': '#FFFFFF',
        'error-container': '#FFEBEE',
        'on-error-container': '#D32F2F',
        outline: '#747878',
        'outline-variant': '#C4C7C7',
        'border-glass': 'rgba(15, 15, 15, 0.12)',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      boxShadow: {
        glass: '0 2px 8px rgba(0, 0, 0, 0.04)',
        'glass-md': '0 10px 25px rgba(0, 0, 0, 0.06)',
        'glass-lg': '0 20px 40px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
};
