/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f7faf9',
        surface: '#f7faf9',
        'surface-dim': '#d7dbda',
        'surface-bright': '#f7faf9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f3',
        'surface-container': '#ebeeed',
        'surface-container-high': '#e6e9e8',
        'surface-container-highest': '#e0e3e2',
        'on-surface': '#181c1c',
        'on-surface-variant': '#444748',
        'inverse-surface': '#2d3131',
        'inverse-on-surface': '#eef1f0',
        primary: '#0f0f0f',
        'on-primary': '#ffffff',
        'primary-container': '#1c1b1b',
        'on-primary-container': '#858383',
        secondary: '#506600',
        'on-secondary': '#ffffff',
        'secondary-container': '#c1f100',
        'on-secondary-container': '#546b00',
        'secondary-fixed': '#c3f400',
        'secondary-fixed-dim': '#abd600',
        tertiary: '#0066ff',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#001849',
        'on-tertiary-container': '#447cff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        outline: '#747878',
        'outline-variant': '#c4c7c7',
        'border-glass': 'rgba(196, 199, 199, 0.25)',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      boxShadow: {
        glass: '0 2px 8px rgba(0, 0, 0, 0.04)',
        'glass-md': '0 10px 25px rgba(0, 0, 0, 0.06)',
        'glass-lg': '0 20px 40px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
};
