import {OutletFieldHistory} from '../OutletValidation/components/OutletFieldHistory';
import {wibDateKey} from '../../../../shared/visit-metrics.mjs';
import React,{useEffect,useState} from 'react';
import {outletValidationApi} from '../../services/api';
import {useFormDraft} from '../../shared/hooks/useFormDraft';
import {useUnsavedNavigation} from '../../shared/hooks/useUnsavedNavigation';
import {DeviceCameraCapture} from '../../shared/components/camera/DeviceCameraCapture';
import {stamp,point} from '../OutletManagement/outletPresentation';
const labels={OPEN:'Perlu dikerjakan',SUBMITTED:'Menunggu pemeriksa',DONE:'Diterima',CANCELLED:'Dibatalkan'};
export function OutletFieldForm({task:t,onSaved}){
 const o=t.review.outlet,v=t.policySnapshot.values,[busy,setBusy]=useState(false),[error,setError]=useState(''),[location,setLocation]=useState(null),[canEditPending,setCanEditPending]=useState(false);
 const draft=useFormDraft(`outlet-field:${t.id}`,()=>({requestId:crypto.randomUUID(),outcome:'FOUND',name:o.name,address:o.address||'',note:'',latitude:null,longitude:null,accuracyMeters:null,capturedAt:null,photo:'',pending:null})),d=draft.value;
 useUnsavedNavigation(t.status==='OPEN'&&draft.dirty,busy);
 useEffect(()=>{if(d.pending&&t.evidence?.requestId===d.pending.requestId){draft.clear();draft.setValue(prev=>({...prev,pending:null,requestId:crypto.randomUUID()}));}},[t.evidence?.requestId,d.pending?.requestId]);
 const expired=t.schedule?.mode==='TODAY_ONLY'&&t.schedule.assignedOn!==wibDateKey();
 const field=(key,value)=>draft.field(key)(value);
 const gps=loc=>{setLocation(loc);};
 const capture=(photo,loc)=>{const g=loc||location;draft.setValue(prev=>({...prev,photo,...(g?{latitude:g.lat??g.latitude,longitude:g.lng??g.longitude,accuracyMeters:g.accuracy??g.accuracyMeters,capturedAt:g.observedAt||null}:{})}));};
 const saveGps=()=>{if(location)draft.setValue(prev=>({...prev,latitude:location.lat??location.latitude,longitude:location.lng??location.longitude,accuracyMeters:location.accuracy??location.accuracyMeters,capturedAt:location.observedAt||null}));};
 const submit=async e=>{e.preventDefault();if(busy)return;const evidence=d.pending||Object.fromEntries(['requestId','outcome','name','address','note','latitude','longitude','accuracyMeters','capturedAt','photo'].map(k=>[k,d[k]]));if(!d.pending&&!draft.persist({...d,pending:evidence})){setError('Identitas pengiriman belum tersimpan di browser. Kosongkan ruang penyimpanan lalu coba kembali.');return;}setBusy(true);setError('');setCanEditPending(false);try{await outletValidationApi.fieldAction(t.id,{action:'SUBMIT',revision:t.revision,evidence});draft.clear();await onSaved();}catch(e){setError(e.message);setCanEditPending([400,403,404,409,422].includes(e.status??e.statusCode));}finally{setBusy(false);}};
 return <section className="ov-section"><h3>{o.name}</h3><p>{t.instructions}</p><p className="ov-muted">{o.address} · {stamp(t.dueAt)}</p><OutletFieldHistory task={t}/>{t.status!=='OPEN'||expired&&!d.pending?<><p>{expired&&t.status==='OPEN'?'Penugasan hari sebelumnya sudah berakhir. Minta SPV menugaskan ulang untuk masuk PJP hari ini.':labels[t.status]}</p>{t.evidence&&<p>{t.evidence.note} · {point(t.evidence)}</p>}</>:<form className="app-form" onSubmit={submit}>{draft.restored&&<p className="ov-notice">{draft.restoreMessage}</p>}{error&&<p className="app-error" role="alert">{error}</p>}{draft.storageError&&<p className="app-error" role="alert">{draft.storageError}</p>}{d.pending&&<p className="ov-notice">Bukti pengiriman dikunci agar percobaan ulang tidak membuat duplikat. Jika koneksi terputus, ulangi pengiriman yang sama. Draf hanya dapat diubah setelah penolakan server yang terkonfirmasi.</p>}
 <fieldset disabled={busy||Boolean(d.pending)} className="app-form"><label className="app-field">Hasil pemeriksaan<select value={d.outcome} onChange={e=>field('outcome',e.target.value)}>{[['FOUND','Toko ditemukan'],['NOT_FOUND','Tidak ditemukan'],['MOVED','Toko pindah'],['CLOSED','Toko tutup']].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="app-field">Nama lengkap di papan toko<input value={d.name} onChange={e=>field('name',e.target.value)} maxLength={200} required={d.outcome==='FOUND'}/></label><label className="app-field">Alamat lengkap (jalan/patokan, nomor atau RT/RW, kelurahan, kecamatan)<textarea value={d.address} onChange={e=>field('address',e.target.value)} maxLength={1000} required={d.outcome==='FOUND'}/></label><label className="app-field">Catatan / usaha pencarian<textarea value={d.note} onChange={e=>field('note',e.target.value)} required minLength={10} maxLength={4000}/></label>
 {!d.pending&&<DeviceCameraCapture onCapture={capture} onLocationChange={gps} capturedPhoto={d.photo} onRetake={()=>field('photo','')} facingModeDefault="environment" requireGps={v.OUTLET_FIELD_REQUIRE_GPS!==false} photoRequired={v.OUTLET_FIELD_REQUIRE_PHOTO!==false} enforceGeofence={false} outletName={o.name} buttonLabel="Ambil foto bukti outlet"/>}<p className="ov-muted">GPS bukti: {point(d)} · akurasi {d.accuracyMeters??'—'} m · {stamp(d.capturedAt)}</p><button type="button" className="app-button" disabled={!location} onClick={saveGps}>Gunakan GPS saat ini</button><p className="ov-muted">GPS/foto mengikuti aturan tugas saat ditugaskan; bukan pengganti absensi.</p></fieldset>
 <div className="app-actions"><button className="app-button app-button-primary" disabled={busy}>{busy?'Mengirim…':d.pending?'Ulangi pengiriman yang sama':'Kirim bukti untuk diperiksa'}</button>{d.pending&&canEditPending&&<button type="button" className="app-button" disabled={busy} onClick={()=>draft.setValue(prev=>({...prev,pending:null,requestId:crypto.randomUUID()}))}>Perbarui draf setelah penolakan</button>}</div></form>}</section>;
}
