import React,{useState} from 'react';
import {useApp} from '../../context/AppContext';
import {TAB_IDS} from '../../constants/navigation';
import {useWorkspaceState} from '../../shared/hooks/useWorkspaceState';
import {useSelectedDetail} from '../../shared/hooks/useSelectedDetail';
import {useSalesOrders} from './hooks/useSalesOrders';
import {SalesOrderDetail} from './components/SalesOrderDetail';
import {orderStatusLabel,fulfillmentLabel,stampWib} from './salesPresentation';
import {OutsidePjpOrderDialog} from './components/OutsidePjpOrderDialog';
export function SalesOrdersPage(){
  const {setActiveTab,settings,user}=useApp();const {orders,loading,error,reload}=useSalesOrders();
  const [outside,setOutside]=useState(false);
  const [query,setQuery]=useWorkspaceState('salesOrderSearch',''),[status,setStatus]=useWorkspaceState('salesOrderStatus','ALL'),[fulfillment,setFulfillment]=useWorkspaceState('salesOrderFulfillment','ALL'),[selectedId,setSelectedId]=useWorkspaceState('salesOrder',''),[page,setPage]=useWorkspaceState('salesOrderPage','1');
  const filtered=orders.filter(o=>`${o.code||o.id} ${o.pjpStop?.outlet?.name||o.customerSnapshot?.name||''}`.toLocaleLowerCase('id-ID').includes(query.trim().toLocaleLowerCase('id-ID'))&&(status==='ALL'||o.status===status)&&(fulfillment==='ALL'||o.fulfillmentStatus===fulfillment)).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
  const selected=orders.find(o=>o.id===selectedId),ref=useSelectedDetail(selected?.id),pages=Math.max(1,Math.ceil(filtered.length/20)),current=Math.min(pages,Math.max(1,Number(page)||1));
  const filterChange=(setter,value)=>{setter(value);setPage('1',{replace:true});};
  return <div className="workspace-page sales-workspace">
    <header className="sales-heading"><div><p className="admin-eyebrow">Sales / Pemantauan</p><h1>Order saya</h1><p>Pantau persetujuan, janji kirim, dan jumlah yang diterima pelanggan dari order Anda.</p></div><div className="app-actions"><button type="button" className="app-button app-button-primary" onClick={()=>setActiveTab(TAB_IDS.SALES_VISITS)}>Buat order melalui kunjungan</button>{settings.ORDER_ALLOW_OUTSIDE_PJP&&user.permissions?.can_create_order!==false&&<button type="button" className="app-button" disabled={settings.FEATURE_ORDERS_MODE!=='ACTIVE'} onClick={()=>setOutside(true)}>Order tanpa PJP</button>}</div></header>
    {outside&&<OutsidePjpOrderDialog onClose={()=>setOutside(false)} onSaved={reload}/>}
    <div className="sales-toolbar"><label className="sales-search">Cari order atau pelanggan<input type="search" value={query} onChange={e=>filterChange(setQuery,e.target.value)} placeholder="Kode order atau nama outlet…"/></label><label>Persetujuan<select value={status} onChange={e=>filterChange(setStatus,e.target.value)}><option value="ALL">Semua persetujuan</option>{['PENDING_APPROVAL','APPROVED','REJECTED'].map(s=><option key={s} value={s}>{orderStatusLabel(s)}</option>)}</select></label><label>Pemenuhan<select value={fulfillment} onChange={e=>filterChange(setFulfillment,e.target.value)}><option value="ALL">Semua pemenuhan</option>{['OPEN','PARTIAL','FULFILLED','CLOSED_WITH_CANCELLATION'].map(s=><option key={s} value={s}>{fulfillmentLabel(s)}</option>)}</select></label><button type="button" className="app-button" disabled={loading} onClick={reload}>Perbarui</button></div>
    {error&&<p role="alert" className="app-error">Order belum dapat dimuat: {error}</p>}{loading&&<p role="status">Memuat order Anda…</p>}
    {!error&&<div className={`sales-split ${selected?'has-selection':''}`}><section className="sales-panel"><div className="sales-table-wrap"><table className="sales-table sales-mobile-cards"><caption className="sr-only">Order Anda, persetujuan dan pemenuhannya</caption><thead><tr>{['Order / pelanggan','Persetujuan','Pemenuhan','Tindakan'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{filtered.slice((current-1)*20,current*20).map(o=><tr key={o.id} aria-selected={o.id===selectedId}><td data-label="Order / pelanggan"><strong>{o.code||o.id.slice(0,8)}</strong><span>{o.pjpStop?.outlet?.name||o.customerSnapshot?.name||'—'}</span><small>{stampWib(o.createdAt)}</small></td><td data-label="Persetujuan">{orderStatusLabel(o.status)}</td><td data-label="Pemenuhan">{o.status==='REJECTED'?'Tidak dilanjutkan':fulfillmentLabel(o.fulfillmentStatus)}<small>Janji kirim: {o.promisedAt?stampWib(o.promisedAt):'Belum ditetapkan'}</small></td><td data-label="Tindakan"><button type="button" className="app-button" aria-pressed={o.id===selectedId} onClick={()=>setSelectedId(o.id)}>Lihat order</button></td></tr>)}</tbody></table></div>{!loading&&!filtered.length&&<div className="sales-empty"><h2>{orders.length?'Tidak ada order sesuai filter':'Belum ada order'}</h2><p>{orders.length?'Ubah pencarian atau filter untuk melihat order lainnya.':'Buat order dari outlet dengan kunjungan yang sedang berlangsung.'}</p></div>}<nav className="sales-pagination" aria-label="Halaman order"><button className="app-button" disabled={current===1||loading} onClick={()=>setPage(String(current-1))}>Sebelumnya</button><span>{filtered.length} order · {current}/{pages}</span><button className="app-button" disabled={current===pages||loading} onClick={()=>setPage(String(current+1))}>Berikutnya</button></nav></section>{selected&&<aside className="sales-panel sales-detail"><div className="sales-detail-heading"><h2 ref={ref} tabIndex={-1}>Detail order</h2><button className="app-button" onClick={()=>setSelectedId('')}>Kembali ke daftar</button></div><SalesOrderDetail order={selected}/></aside>}</div>}
  </div>;
}
