import React,{useState} from 'react';
import {useApp} from '../../../context/AppContext';
import {NativeDialog} from '../../../shared/components/common/NativeDialog';
import {BusinessCodeInput} from '../../../shared/components/common/BusinessCodeInput';
export function AdminFinalizeModal({item,isProcessing,onClose,onConfirmFinalize,error}) {
 const {clusters}=useApp(),[clusterId,setClusterId]=useState(item?.clusterId || ''),[customerCode,setCustomerCode]=useState(item?.customerCode || ''),[duplicateReason,setDuplicateReason]=useState('');
 if(!item)return null;
 return <NativeDialog open title="Aktifkan outlet" busy={isProcessing} onClose={onClose}><form className="app-form" onSubmit={e=>{e.preventDefault();onConfirmFinalize(item.id,customerCode.trim(),clusterId,duplicateReason);}}><p><strong>{item.name}</strong> akan menjadi master outlet aktif.</p><p className="outlet-muted">Pemeriksaan peta bersifat opsional. Aktivasi tidak menerbitkan jadwal PJP secara otomatis.</p><div aria-live="polite">{error&&<p className="app-error" role="alert">{error}</p>}</div><BusinessCodeInput entity="OUTLET" value={customerCode} onChange={setCustomerCode} disabled={isProcessing}/><label className="app-field">Wilayah<select required disabled={isProcessing} value={clusterId} onChange={e=>setClusterId(e.target.value)}><option value="">Pilih wilayah</option>{clusters.filter(c=>!c.deletedAt&&(!c.tradeType||c.tradeType===item.channel)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><details className="outlet-disclosure"><summary>Jika sistem menemukan kemungkinan outlet ganda</summary><p className="outlet-muted">Periksa kandidat pada master terlebih dahulu. Isi hanya bila toko memang berbeda.</p><label className="app-field">Alasan outlet berbeda<textarea minLength={10} maxLength={1000} disabled={isProcessing} value={duplicateReason} onChange={e=>setDuplicateReason(e.target.value)}/></label></details><footer className="outlet-form-footer"><button type="button" className="app-button" disabled={isProcessing} onClick={onClose}>Batal</button><button type="submit" className="app-button app-button-primary" disabled={isProcessing}>{isProcessing?'Mengaktifkan…':'Simpan & aktifkan'}</button></footer></form></NativeDialog>;
}
