import {REGISTRATION_FIELDS,requiredRegistrationFields,registrationFieldError} from '../../../../../shared/registration-fields.mjs';
import React,{useState} from 'react';
import {useApp} from '../../../context/AppContext';
import {NativeDialog} from '../../../shared/components/common/NativeDialog';
import {BusinessCodeInput} from '../../../shared/components/common/BusinessCodeInput';
import {registrationLocation} from '../../../../../shared/registration-policy.mjs';
export function AdminFinalizeModal({item,isProcessing,onClose,onConfirmFinalize,error}) {
 const {clusters}=useApp(),[clusterId,setClusterId]=useState(item?.clusterId || ''),[customerCode,setCustomerCode]=useState(item?.customerCode || ''),[duplicateReason,setDuplicateReason]=useState('');
 const [latitude,setLatitude]=useState(item?.latitude??''),[longitude,setLongitude]=useState(item?.longitude??''),[locationError,setLocationError]=useState('');
 const [fields,setFields]=useState(()=>Object.fromEntries(Object.keys(REGISTRATION_FIELDS).map(key=>[key,item?.[key]||''])));
 if(!item)return null;
 const requiredFields=requiredRegistrationFields(item.policySnapshot?.values?.REGISTRATION_ACTIVATION_REQUIRED_FIELDS||'');
 const required=item.policySnapshot?.values?.REGISTRATION_ACTIVATION_REQUIRE_LOCATION!==false;
 const submit=e=>{e.preventDefault();setLocationError('');const fieldError=registrationFieldError(fields,requiredFields.join(','),'aktivasi');if(fieldError){setLocationError(fieldError);return;}let point;try{point=registrationLocation({latitude:latitude===''?null:Number(latitude),longitude:longitude===''?null:Number(longitude)},required);}catch(err){setLocationError(err.message);return;}onConfirmFinalize(item.id,customerCode.trim(),clusterId,duplicateReason,{...point,registrationFields:Object.fromEntries(requiredFields.map(key=>[key,fields[key].trim()]))});};
 return <NativeDialog open title="Aktifkan outlet" busy={isProcessing} onClose={onClose}><form className="app-form" onSubmit={submit}><p><strong>{item.name}</strong> akan menjadi master outlet aktif.</p><p className="outlet-muted">Pemeriksaan peta bersifat opsional. Aktivasi tidak menerbitkan jadwal PJP secara otomatis.</p><div aria-live="polite">{error&&<p className="app-error" role="alert">{error}</p>}</div><BusinessCodeInput entity="OUTLET" value={customerCode} onChange={setCustomerCode} disabled={isProcessing}/><label className="app-field">Wilayah<select required disabled={isProcessing} value={clusterId} onChange={e=>setClusterId(e.target.value)}><option value="">Pilih wilayah</option>{clusters.filter(c=>!c.deletedAt&&(!c.tradeType||c.tradeType===item.channel)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><fieldset disabled={isProcessing} className="grid gap-3"><legend>Koordinat fisik outlet {required?'(wajib)':'(opsional)'}</legend><p className="outlet-muted">Lengkapi dari referensi yang telah diperiksa. Titik yang diubah di sini dicatat sebagai input manual, bukan GPS Sales atau hasil Google. Titik kosong tidak diganti dengan nol.</p><div className="grid gap-3 sm:grid-cols-2"><label className="app-field">Lintang<input type="number" min="-90" max="90" step="any" required={required||longitude!==''} value={latitude} onChange={e=>setLatitude(e.target.value)}/></label><label className="app-field">Bujur<input type="number" min="-180" max="180" step="any" required={required||latitude!==''} value={longitude} onChange={e=>setLongitude(e.target.value)}/></label></div>{locationError&&<p role="alert" className="app-error">{locationError}</p>}</fieldset>{!!requiredFields.length&&<fieldset disabled={isProcessing} className="grid gap-3"><legend>Data wajib sebelum aktivasi</legend><p className="outlet-muted">Perubahan dicatat pada riwayat aktivasi bersama petugas dan nilai sebelumnya.</p>{requiredFields.map(key=><label className="app-field" key={key}>{REGISTRATION_FIELDS[key]}<input required maxLength={2000} value={fields[key]} onChange={e=>setFields(current=>({...current,[key]:e.target.value}))}/></label>)}</fieldset>}<details className="outlet-disclosure"><summary>Jika sistem menemukan kemungkinan outlet ganda</summary><p className="outlet-muted">Periksa kandidat pada master terlebih dahulu. Isi hanya bila toko memang berbeda.</p><label className="app-field">Alasan outlet berbeda<textarea minLength={10} maxLength={1000} disabled={isProcessing} value={duplicateReason} onChange={e=>setDuplicateReason(e.target.value)}/></label></details><footer className="outlet-form-footer"><button type="button" className="app-button" disabled={isProcessing} onClick={onClose}>Batal</button><button type="submit" className="app-button app-button-primary" disabled={isProcessing}>{isProcessing?'Mengaktifkan…':'Simpan & aktifkan'}</button></footer></form></NativeDialog>;
}
