import React,{useState,useEffect,useCallback} from 'react';
import {staffAttendanceApi} from '../../../services/api';
export const FollowUpPanel=()=>{
 const [loading,setLoading]=useState(true);const [rows,setRows]=useState([]);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [notes,setNotes]=useState({});
 const reload=useCallback(async()=>{try{const res=await staffAttendanceApi.getFollowUps();setRows(res.data);setError('');}finally{setLoading(false);}},[]);
 useEffect(()=>{reload().catch(e=>setError(e.message));const tick=setInterval(()=>reload().catch(e=>setError(e.message)),60000);return()=>clearInterval(tick);},[reload]);
 const complete=async e=>{e.preventDefault();const id=e.currentTarget.dataset.id;setBusy(id);setError('');try{await staffAttendanceApi.completeFollowUp(id,notes[id]);await reload();}catch(e){setError(e.message);}finally{setBusy('');}};
 return <section className="followup-panel"><h3>Tindak lanjut audit</h3>{error&&<p role="alert" className="text-red-600">{error}</p>}{loading&&<p role="status">Memuat tugas audit…</p>}{!loading&&!error&&!rows.length&&<p className="text-sm text-on-surface-variant">Tidak ada tugas audit yang menunggu.</p>}{rows.map(r=><div key={r.id} className="workspace-card"><p className="font-medium">{r.outletName} · {r.followUp.status==='DONE'?'Selesai':'Terbuka'}</p><p>{r.followUp.note}</p><p className="text-sm">Tenggat {r.followUp.dueDate}</p>{r.followUp.status==='DONE'?<p>{r.followUp.completionNote}</p>:<form data-id={r.id} onSubmit={complete} className="flex flex-wrap gap-2"><input aria-label="Catatan penyelesaian" required maxLength={4000} className="form-input flex-1 min-w-0" value={notes[r.id]||''} onChange={e=>setNotes({...notes,[r.id]:e.target.value})}/><button type="submit" disabled={Boolean(busy)} className="btn btn-secondary">{busy===r.id?'Menyimpan…':'Selesaikan'}</button></form>}</div>)}</section>;
};
