import React,{useEffect,useState} from 'react';
import {outletValidationApi} from '../../../services/api';
import {useApp} from '../../../context/AppContext';
export function OutletValidationAttendanceReport({date,salesmanId,search,refreshKey}){
 const {user}=useApp(),[data,setData]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 const allowed=['ADMIN','SUPERVISOR'].includes(user?.role)&&user?.permissions?.can_validate_outlet;
 useEffect(()=>{const update=()=>setRevision(v=>v+1);window.addEventListener('operational-data-changed',update);window.addEventListener('focus',update);return()=>{window.removeEventListener('operational-data-changed',update);window.removeEventListener('focus',update);};},[]);
 useEffect(()=>{setPage(1);},[date,salesmanId,search]);
 useEffect(()=>{if(!allowed)return;let active=true;setLoading(true);setError('');outletValidationApi.fieldVisitReport({date,page,salesmanId,search}).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[date,page,allowed,user?.id,salesmanId,search,refreshKey,revision]);
 if(!allowed)return null;
 const labels={COMPLETE:'Validasi selesai',RESOLVED:'Kasus selesai · tidak perlu kunjungan lagi',PENDING:'Belum dikunjungi · PJP tidak lengkap',RETURNED:'Bukti dikembalikan · perlu validasi ulang',WAITING_REVIEW:'Bukti menunggu SPV',ACCEPTED:'Bukti diterima',CANCELLED:'Penugasan dibatalkan',REASSIGNED:'Penugasan dialihkan'};
 return <section className="ov-section"><h3>Rekap PJP validasi outlet</h3><p className="ov-muted">Flag yang belum dikerjakan tetap tersimpan pada hari penugasan meskipun tugas hanya berlaku sehari. Bukti validasi terpisah dari IN/OUT presensi dan tidak menjadi penjualan.</p>{error&&<p role="alert" className="app-error">{error}</p>}{loading?<p role="status">Memuat rekap validasi…</p>:<><div className="ov-table-wrap"><table className="ov-table"><thead><tr><th>Sales / PJP</th><th>Outlet</th><th>Hasil hari tersebut</th><th>Mode agenda</th></tr></thead><tbody>{data?.data.map(r=><tr key={r.id}><td>{r.pjp.user.name}<small>{r.pjp.code}</small></td><td>{r.outlet.name}<small>{r.outlet.address}</small></td><td><strong className={r.validationFlag?'app-error':''}>{labels[r.validationResult?.state]||'Belum dikerjakan'}</strong>{r.validationResult?.submittedAt&&<small>Bukti dikirim {new Date(r.validationResult.submittedAt).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})}</small>}</td><td>{r.validationResult?.mode==='UNTIL_COMPLETE'?'Sampai selesai':'Hanya hari penugasan'}</td></tr>)}{!data?.data.length&&<tr><td colSpan={4}>Tidak ada tugas validasi pada tanggal ini.</td></tr>}</tbody></table></div><div className="app-actions"><button type="button" className="app-button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><span>{page} / {data?.pagination.totalPages||1}</span><button type="button" className="app-button" disabled={page>=(data?.pagination.totalPages||1)} onClick={()=>setPage(p=>p+1)}>Berikutnya</button></div></>}</section>;
}
