import React,{useState,useEffect} from 'react';
import {routeChangesApi} from '../../../services/api';
import {wibInputToIso} from '../../../../../shared/assignment-schedules.mjs';
import {useApp} from '../../../context/AppContext';
export function RouteReviewAssignmentEditor({id,onChanged}){
 const {settings}=useApp();
 const [options,setOptions]=useState(null),[owner,setOwner]=useState(''),[due,setDue]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;routeChangesApi.assignmentOptions(id).then(r=>{if(alive){setOptions(r.data);setOwner(r.data.assignment?.ownerId||'');setDue(r.data.assignment?.dueAt?new Date(Date.parse(r.data.assignment.dueAt)+7*3600000).toISOString().slice(0,16):'');}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[id]);
 const save=async e=>{e.preventDefault();if(!options||busy)return;setBusy(true);setError('');try{await routeChangesApi.assignReview(id,{ownerId:owner||null,stage:options.stage,revision:options.revision,dueAt:owner?wibInputToIso(due):null,reason});await onChanged();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <details className="rounded-xl border p-3"><summary className="cursor-pointer font-semibold">Penugasan pemeriksa rute</summary><p className="text-sm my-3">Penugasan berlaku untuk kasus dan tahap ini saja. Delegasi sementara/bertanggal tersedia pada Parameter Admin. Mengubah PIC di sini menggantikan penugasan sebelumnya.</p>{settings.ROUTE_REVIEW_ALLOW_DELEGATION===false&&<p className="app-notice">Penugasan pemeriksa baru dinonaktifkan. Anda tetap dapat melepas PIC agar kembali mengikuti alur/tim.</p>}{error&&<p role="alert" className="app-error">{error}</p>}{options&&<form className="space-y-3" onSubmit={save}><fieldset disabled={busy} className="space-y-3"><p>Tahap: {options.stage==='ADMIN'?'Keputusan Admin':'Keputusan awal'}</p><label className="block">Pemeriksa<select className="form-input w-full" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Ikuti pemeriksa sesuai alur / tim</option>{options.people.map(p=><option key={p.id} value={p.id} disabled={settings.ROUTE_REVIEW_ALLOW_DELEGATION===false}>{p.name} · {p.role}</option>)}</select></label>{owner&&<label className="block">Tenggat (WIB)<input required type="datetime-local" className="form-input w-full" value={due} onChange={e=>setDue(e.target.value)}/></label>}<label className="block">Alasan perubahan<textarea required minLength={5} maxLength={2000} className="form-input w-full" value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="app-button" disabled={busy||Boolean(owner)&&settings.ROUTE_REVIEW_ALLOW_DELEGATION===false}>{busy?'Menyimpan…':'Simpan penugasan'}</button></fieldset></form>}</details>;
}
