import React from 'react';
export function RegistrationIdentitySection({LOCATION_OPTIONS,formData,handleNameChange,handleSelectGooglePlace,handleUnlockGooglePlace,hasSearched,isDebouncing,isSearchingPlace,placeSearchError,placeSearchResults,setHasSearched,settings,updateField,verifiedPlace}) {
  const lookupEnabled=settings.FEATURE_MAPS_MODE==='ACTIVE'&&settings.PLACE_LOOKUP_PROVIDER!=='OFF';
  return <div className="sales-registration-fields">
    <label className="sales-registration-field sales-field-full">Nama outlet <span className="sales-note">Wajib. {lookupEnabled?'Pencarian tempat dimulai setelah nama diketik.':'Pencarian peta nonaktif. Isi alamat manual dan ambil GPS outlet.'}</span><input required minLength={2} value={formData.name} onChange={handleNameChange} placeholder="Nama toko atau pelanggan" autoComplete="organization" /></label>
    {(isDebouncing||isSearchingPlace)&&<p className="sales-note sales-field-full" role="status">{isSearchingPlace?'Mencari tempat…':'Menunggu nama selesai diketik…'}</p>}
    {placeSearchError&&<p className="sales-note sales-field-full" role="alert">{placeSearchError}</p>}
    {verifiedPlace&&<div className="sales-place-selection sales-field-full"><div><strong>Tempat terhubung</strong><p>{verifiedPlace.name}</p></div><button type="button" className="app-button" onClick={handleUnlockGooglePlace}>Lepas pilihan</button></div>}
    {placeSearchResults.length>0&&!isSearchingPlace&&!isDebouncing&&<div className="sales-place-results sales-field-full" aria-label="Hasil pencarian tempat"><p className="sales-note">Pilih tempat yang sesuai{settings.CUSTOMER_REG_ENFORCE_PLACES_RADIUS?` dalam radius ${settings.CUSTOMER_REG_PLACES_RADIUS_METERS} m`:''}.</p>{placeSearchResults.map((place,index)=><button type="button" key={place.placeId||index} onClick={()=>{handleSelectGooglePlace(place);setHasSearched(false);}}><strong>{place.name}</strong><span>{place.address}</span>{place.distanceMeters!=null&&<small>Jarak {place.distanceMeters} m {place.distanceOrigin==='OFFICE_SEARCH_BIAS'?'dari kantor (acuan pencarian)':'dari GPS perangkat'}</small>}</button>)}</div>}
    {lookupEnabled&&!placeSearchError&&hasSearched&&!placeSearchResults.length&&!isSearchingPlace&&!isDebouncing&&formData.name?.trim().length>=2&&!verifiedPlace&&<p className="sales-note sales-field-full" role="status">Belum ada hasil tempat yang dapat dipilih. Lengkapi alamat manual dan ambil GPS outlet.</p>}
    <label className="sales-registration-field sales-field-full">Alamat outlet <span className="sales-note">Wajib. Periksa kembali alamat dari hasil pencarian.</span><textarea required rows={3} value={formData.address} onChange={e=>updateField('address',e.target.value)} placeholder="Jalan, nomor bangunan, dan wilayah" autoComplete="street-address" /></label>
    <label className="sales-registration-field">Nomor telepon<input type="tel" value={formData.phone} onChange={e=>updateField('phone',e.target.value)} placeholder="08…" autoComplete="tel" /></label>
    <label className="sales-registration-field">Pemilik / penanggung jawab<input value={formData.ownerName} onChange={e=>updateField('ownerName',e.target.value)} autoComplete="name" /></label>
    <label className="sales-registration-field">Lokasi fisik<select value={formData.locationType} onChange={e=>updateField('locationType',e.target.value)}>{LOCATION_OPTIONS.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
    <div className="sales-registration-field"><span>Kode outlet</span><p className="sales-form-help sales-note">Ditetapkan Admin setelah pengajuan diproses.</p></div>
  </div>;
}
