import {OutletQualityFlag} from './OutletQualityFlag';
import React,{useState} from 'react';
import {useApp} from '../../context/AppContext';
import {TAB_IDS} from '../../constants/navigation';
import {useWorkspaceState} from '../../shared/hooks/useWorkspaceState';
import {OutletMiniMapPreview} from '../OutletValidation/components/OutletMiniMapPreview';
import {OutletCoordinateForm} from '../OutletValidation/components/OutletCoordinateForm';
import {OutletReviewRequest} from './OutletReviewRequest';
import {OutletActivationDialog} from './OutletActivationDialog';
import {confirmWorkspaceNavigation} from '../../shared/utils/confirmWorkspaceNavigation';
import {OutletHistory} from './OutletHistory';
import {point,stamp,reviewResult,reviewLabels,subChannels} from './outletPresentation';
export function OutletProfile({outlet:o,canManage,onEdit,onSaved,onRefresh}) {
 const {user,setActiveTab}=useApp(),[tab,setTab]=useState('IDENTITY'),[correction,setCorrection]=useState(false),[request,setRequest]=useState(false),[activation,setActivation]=useState(false),[,selectReview]=useWorkspaceState('outletReview','');
 const canReview=['ADMIN','SUPERVISOR'].includes(user.role)?user.permissions?.can_validate_outlet!==false:Boolean(user.permissions?.can_validate_outlet),review=o.reviews?.[0];
 const openReview=review=>{selectReview(review.id);setActiveTab(TAB_IDS.OUTLET_VALIDATION);};
 return <div className="outlet-profile-body"><header><div className="outlet-profile-title"><div><p className="outlet-eyebrow">{o.outletCode || 'Kode belum tersedia'}</p><h2>{o.name}</h2></div><span className="outlet-badge">{o.deletedAt?'Nonaktif':'Aktif'}</span></div><p className="outlet-muted">{o.address}</p></header>
  <OutletQualityFlag outlet={o}/>
  <nav className="outlet-tabs" aria-label="Bagian profil">{[['IDENTITY','Identitas'],['LOCATION','Lokasi'],['ACTIVITY','Operasional'],['HISTORY','Riwayat']].map(([id,label])=><button type="button" key={id} aria-pressed={tab===id} onClick={()=>{if(confirmWorkspaceNavigation()){setTab(id);setCorrection(false);}}}>{label}</button>)}</nav>
  {tab==='IDENTITY'&&<><dl className="outlet-facts"><dt>Pemilik</dt><dd>{o.ownerName || 'Belum diisi'}</dd><dt>Telepon</dt><dd>{o.phone?<a href={`tel:${o.phone}`}>{o.phone}</a>:'Belum diisi'}</dd><dt>Channel</dt><dd>{o.channel==='MODERN_TRADE'?'Modern Trade':'General Trade'} · {subChannels[o.subChannel] || o.subChannel}</dd><dt>Wilayah</dt><dd>{o.cluster?.name || 'Belum tersedia'}</dd><dt>Sales wilayah</dt><dd>{o.cluster?.assignedSales?.name || 'Belum ditugaskan'}</dd><dt>Sumber data</dt><dd>{o.registrationId?'Pengajuan outlet':'Master / impor'}{o.registration?.registrationCode&&` · ${o.registration.registrationCode}`}</dd></dl><details className="outlet-disclosure"><summary>Identitas pajak / NIK</summary><dl className="outlet-facts"><dt>Status</dt><dd>{o.taxType==='PKP'?'PKP':'Non PKP'}</dd><dt>{o.taxType==='PKP'?'NPWP':'NIK'}</dt><dd>{o.taxNumber || 'Belum diisi'}</dd><dt>Nama dokumen</dt><dd>{o.taxName || 'Belum diisi'}</dd><dt>Alamat dokumen</dt><dd>{o.taxAddress || 'Belum diisi'}</dd></dl></details>{canManage&&!o.deletedAt&&<button type="button" className="app-button app-button-primary" onClick={onEdit}>Edit identitas</button>}</>}
  {tab==='LOCATION'&&<><OutletMiniMapPreview latitude={o.latitude} longitude={o.longitude} name={o.name} radiusMeters={o.radiusMeters}/><dl className="outlet-facts"><dt>Titik master</dt><dd>{point(o)}</dd><dt>Radius presensi</dt><dd>{o.radiusMeters} m</dd><dt>Sumber titik</dt><dd>{o.locationEvidence?.source || 'Belum tercatat'}{o.locationEvidence?.accuracyMeters!=null&&` · akurasi perangkat ±${Math.round(o.locationEvidence.accuracyMeters)} m`}</dd><dt>Pemeriksaan peta</dt><dd>{reviewResult(o)}</dd><dt>Terakhir diperiksa</dt><dd>{o.validatedAt?stamp(o.validatedAt):'Belum diperiksa · opsional'}</dd></dl><p className="outlet-muted">Pemeriksaan peta dilakukan bila data diragukan. Status pemeriksaan terpisah dari status aktif outlet.</p>{!o.deletedAt&&<div className="app-actions">{(canManage||canReview)&&<button type="button" className="app-button" onClick={()=>{if(!correction||confirmWorkspaceNavigation())setCorrection(v=>!v);}}>Koreksi lokasi</button>}{canReview&&<button type="button" className="app-button" onClick={()=>review&&review.status!=='COMPLETED'?openReview(review):setRequest(true)}>{review&&review.status!=='COMPLETED'?'Buka kasus pemeriksaan':'Ajukan pemeriksaan opsional'}</button>}</div>}{correction&&<OutletCoordinateForm outlet={o} onSaved={onSaved} onClose={()=>setCorrection(false)}/>}</>}
  {tab==='ACTIVITY'&&<><dl className="outlet-facts"><dt>Stop PJP mendatang</dt><dd>{o.operational.scheduled}</dd><dt>Order terbuka</dt><dd>{o.operational.orders}</dd><dt>Packing belum selesai</dt><dd>{o.operational.packing}</dd><dt>Pengiriman berjalan</dt><dd>{o.operational.deliveries}</dd><dt>Frekuensi master</dt><dd>{o.itineraryCode?`${o.itineraryCode} · setiap ${o.itineraryCode.slice(1)} minggu`:'Belum ditetapkan'}</dd><dt>Pemeriksaan terakhir</dt><dd>{review?reviewLabels[review.status]:'Tidak diajukan'}</dd></dl>{o.visitSchedule&&<p className="outlet-muted">Usulan kunjungan pengajuan: {o.visitSchedule.days || 'Hari belum dipilih'} · {o.visitSchedule.intervalWeeks?`setiap ${o.visitSchedule.intervalWeeks} minggu`:o.visitSchedule.weekType || 'Interval belum ditetapkan'}. Tinjau melalui planner.</p>}<p className="outlet-muted">Outlet aktif baru masuk jadwal setelah Supervisor menyusun dan menerbitkan PJP.</p><button type="button" className="app-button" onClick={()=>setActiveTab(TAB_IDS.ROUTE_PLANNING)}>Buka wilayah & PJP</button>{canManage&&<button type="button" className={`app-button ${o.deletedAt?'':'outlet-danger'}`} onClick={()=>setActivation(true)}>{o.deletedAt?'Aktifkan kembali':'Nonaktifkan outlet'}</button>}</>}
  {tab==='HISTORY'&&<OutletHistory outlet={o}/>}
  {request&&<OutletReviewRequest outlets={[o]} onClose={()=>{setRequest(false);onRefresh();}} onSaved={r=>{setRequest(false);openReview(r[0]);}}/>}
  {activation&&<OutletActivationDialog outlet={o} onClose={()=>setActivation(false)} onSaved={onSaved}/>}
 </div>;
}
