import {useFeaturePolicy} from '../../shared/hooks/useFeaturePolicy';
import React,{useState} from 'react';
import {outletOperationalPoint} from '../../../../shared/outlet-location.mjs';
import {request} from '../../services/httpClient';
import {GoogleOutletMap} from '../OutletValidation/components/GoogleOutletMap';
export function OutletOperationalLocation({outlet,canRefresh,onRefresh}){
 const policy=useFeaturePolicy('OUTLET_REVIEW');
 const p=outletOperationalPoint(outlet),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 if(p.source!=='GOOGLE')return <p className="outlet-muted">Rute dan radius memakai titik internal. Koreksi GPS lapangan dicatat sebagai bukti tersendiri.</p>;
 const refresh=async()=>{setBusy(true);setMessage('');try{const r=await request(`/outlets/${outlet.id}/google-location/refresh`,{method:'POST'});setMessage(r.data.lastError&&r.data.status==='ACTIVE'?'Pembaruan belum berhasil. Masa berlaku titik sebelumnya tetap berlaku.':r.data.status==='ACTIVE'?'Lokasi berhasil diperbarui.':'Lokasi perlu diperiksa ulang sebelum digunakan.');await onRefresh();}catch(e){setMessage(e.message);}finally{setBusy(false);}};
 return <section className="outlet-disclosure" aria-label="Lokasi operasional Google"><h3>Lokasi operasional</h3><dl className="outlet-facts"><dt>Sumber</dt><dd><a translate="no" href="https://maps.google.com" target="_blank" rel="noreferrer">Google Maps</a> · terpisah dari GPS lapangan</dd><dt>Status</dt><dd>{p.status==='ACTIVE'?'Siap untuk rute dan radius':'Perlu pemeriksaan ulang · titik tidak digunakan'}</dd><dt>Berlaku sampai</dt><dd>{p.expiresAt?new Date(p.expiresAt).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})+' WIB':'Tidak tersedia'}</dd></dl>{p.status==='ACTIVE'&&<><GoogleOutletMap outlet={outlet} candidate={p} approved/><a className="app-button" href={`https://www.google.com/maps/search/?api=1&query=${p.latitude},${p.longitude}&query_place_id=${encodeURIComponent(p.placeId)}`} target="_blank" rel="noreferrer">Buka Google Maps</a></>}<p className="outlet-muted">Titik kedaluwarsa atau berubah tidak diganti otomatis dengan koordinat lama yang diragukan. Gunakan pemeriksaan outlet untuk persetujuan baru.</p>{outlet.googleLocation?.approvalMode==='ADMIN_REVIEW'&&<p className="outlet-muted">Lokasi dipilih melalui pertimbangan Admin. Gunakan pemeriksaan outlet baru untuk meninjau ulang sebelum masa berlaku berakhir.</p>}{canRefresh&&outlet.googleLocation?.approvalMode!=='ADMIN_REVIEW'&&policy.canStart&&policy.settings.OUTLET_GOOGLE_LOCATION_ENABLED!==false&&policy.settings.OUTLET_MAP_COMPARISON_ENABLED!==false&&p.status==='ACTIVE'&&!outlet.deletedAt&&<button type="button" className="app-button" disabled={busy} onClick={refresh}>{busy?'Memperbarui…':'Perbarui dari Google'}</button>}{message&&<p role="status" className="outlet-muted">{message}</p>}</section>;
}
