import React,{useState,useRef} from 'react';
import {NativeDialog} from '../../shared/components/common/NativeDialog';
import {outletValidationApi} from '../../services/api';
import {useFormDraft} from '../../shared/hooks/useFormDraft';
import {useFeaturePolicy} from '../../shared/hooks/useFeaturePolicy';
export function OutletReviewRequest({outlets,onClose,onSaved}){
 const draft=useFormDraft(`outlet-batch:${outlets.map(o=>o.id).sort().join(',')}`,()=>({reason:'',run:false,requestId:crypto.randomUUID(),pending:null})),d=draft.value;
 const {settings}=useFeaturePolicy('OUTLET_REVIEW');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(0),[failures,setFailures]=useState([]),[completed,setCompleted]=useState([]),[confirmedFailure,setConfirmedFailure]=useState(false);
 const stop=useRef(false);
 const submit=async e=>{e.preventDefault();if(busy)return;stop.current=false;setBusy(true);setError('');setConfirmedFailure(false);setProgress(completed.length);const done=[...completed],failed=[];
  try{
   if(d.run){const body=d.pending||{requestId:d.requestId,outletIds:outlets.map(o=>o.id),reason:d.reason};if(!d.pending&&!draft.persist({...d,pending:body}))throw new Error('Identitas batch belum tersimpan di browser. Kosongkan ruang penyimpanan lalu coba kembali.');await outletValidationApi.startJob(body);draft.clear();await onSaved([]);return;}
   for(const o of outlets.filter(o=>!done.some(r=>r.outletId===o.id))){if(stop.current)break;try{const r=await outletValidationApi.openReview(o.id,{reason:d.reason});done.push(r.data);}catch(e){failed.push({id:o.id,name:o.name,error:e.message});}setProgress(p=>p+1);}
   setCompleted(done);setFailures(failed);if(done.length===outlets.length){draft.clear();await onSaved(done);}
  }catch(e){setError(e.message);setConfirmedFailure([400,403,404,409,422].includes(e.status));}finally{setBusy(false);}
 };
 return <NativeDialog open title="Ajukan pemeriksaan opsional" busy={busy} onClose={onClose}><form className="app-form" onSubmit={submit}><p>{outlets.length===1?outlets[0].name:`${outlets.length} outlet dipilih secara eksplisit`}</p><p className="outlet-muted">Untuk data lama atau data diragukan. Validasi tidak mengubah status aktif outlet.</p>{draft.restored&&<p className="outlet-muted">{draft.restoreMessage}</p>}<label className="app-field">Alasan pemeriksaan<textarea required minLength={10} maxLength={1000} value={d.reason} disabled={busy||Boolean(d.pending)||completed.length>0} onChange={e=>draft.field('reason')(e.target.value)}/></label><label className="outlet-check"><input type="checkbox" checked={d.run} disabled={busy||Boolean(d.pending)||completed.length>0||failures.length>0} onChange={e=>draft.field('run')(e.target.checked)}/> Periksa dengan Google melalui batch tersimpan di server</label>
 {d.run&&<p className="outlet-muted">Maksimal {settings.OUTLET_REVIEW_MAX_CALLS??6} panggilan per outlet · {outlets.length*(settings.OUTLET_REVIEW_MAX_CALLS??6)} panggilan untuk pilihan ini. {Number(settings.OUTLET_REVIEW_ESTIMATED_CALL_RUPIAH)>0?`Batas perkiraan Rp ${(outlets.length*(settings.OUTLET_REVIEW_MAX_CALLS??6)*settings.OUTLET_REVIEW_ESTIMATED_CALL_RUPIAH).toLocaleString('id-ID')}.`:'Estimasi biaya belum diisi Admin.'} Pemakaian sebenarnya bergantung hasil dan batas kuota. Progres dapat dilihat pada Validasi outlet.</p>}
 {busy&&<p role="status">{d.run?'Menyimpan batch ke antrean server…':`Membuka kasus ${Math.min(progress+1,outlets.length)} / ${outlets.length}…`}</p>}{error&&<p role="alert" className="app-error">{error}</p>}{draft.storageError&&<p role="alert" className="app-error">{draft.storageError}</p>}{d.pending&&!busy&&<p className="outlet-muted">Isi batch dikunci agar pengiriman ulang memakai identitas yang sama. Periksa daftar batch bila respons belum pasti.</p>}{failures.length>0&&<div className="app-error" role="alert"><p>{completed.length} kasus dibuka, {failures.length} perlu diulang.</p>{failures.map(f=><p key={f.id}>{f.name}: {f.error}</p>)}</div>}
 {!d.run&&<progress max={outlets.length} value={Math.min(progress,outlets.length)} aria-label="Kemajuan pembukaan kasus"/>}<div className="app-actions">{busy&&!d.run&&<button type="button" className="app-button" onClick={()=>{stop.current=true;}}>Hentikan setelah outlet berjalan</button>}{confirmedFailure&&d.pending&&<button type="button" className="app-button" onClick={()=>{draft.setValue(prev=>({...prev,pending:null,requestId:crypto.randomUUID()}));setConfirmedFailure(false);}}>Perbaiki isian setelah penolakan</button>}<button type="button" className="app-button" disabled={busy} onClick={onClose}>Tutup</button><button className="app-button app-button-primary" disabled={busy||!outlets.length}>{busy?'Memproses…':d.pending?'Kirim ulang batch yang sama':failures.length?'Ulangi yang belum berhasil':d.run?'Mulai batch Google':'Buka kasus pemeriksaan'}</button></div></form></NativeDialog>;
}
