import React from 'react';
import {reviewLabels} from './outletPresentation';
export function OutletDirectory({directory:d,selected,onSelect}) {
 return <section className="outlet-panel" aria-label="Direktori outlet"><div className="outlet-toolbar"><label className="app-field"><span>Cari outlet</span><input type="search" value={d.search} onChange={e=>d.setSearch(e.target.value)} placeholder="Nama, kode, alamat atau kontak"/></label><label className="app-field"><span>Wilayah</span><select value={d.cluster} onChange={e=>d.setCluster(e.target.value)}><option value="">Semua wilayah</option>{d.clusters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="app-field"><span>Status</span><select value={d.status} onChange={e=>d.setStatus(e.target.value)}><option value="ACTIVE">Aktif</option><option value="INACTIVE">Nonaktif</option><option value="ALL">Semua</option></select></label></div>
  <div className="outlet-list-heading"><span>{d.loading?'Memuat direktori…':`${d.pagination.total} outlet ditemukan`}</span><button type="button" className="app-button" onClick={d.load} disabled={d.loading}>Perbarui</button></div>
  {d.error?<div className="app-error" role="alert">{d.error}<button type="button" className="app-button" onClick={d.load}>Coba lagi</button></div>:<div className="outlet-table-wrap"><table className="outlet-table"><thead><tr><th>Outlet</th><th>Wilayah / Sales</th><th>Status</th></tr></thead><tbody>{d.data.map(o=><tr key={o.id} aria-selected={selected===o.id}><td><button type="button" className="outlet-name" onClick={()=>onSelect(o.id)}>{o.name}</button><small>{o.outletCode || 'Kode belum tersedia'} · {o.channel==='MODERN_TRADE'?'MT':'GT'}</small><p>{o.address}</p></td><td>{o.cluster?.name || 'Wilayah belum tersedia'}<small>{o.cluster?.assignedSales?.name || 'Sales belum ditugaskan'}</small></td><td><span className="outlet-badge">{o.deletedAt?'Nonaktif':'Aktif'}</span>{o.reviews?.[0]&&<small>Pemeriksaan: {reviewLabels[o.reviews[0].status]}</small>}</td></tr>)}{!d.data.length&&!d.loading&&<tr><td colSpan="3"><p className="app-empty">Tidak ada outlet sesuai filter.</p></td></tr>}</tbody></table></div>}
  <div className="outlet-pagination"><button type="button" className="app-button" disabled={d.loading||d.page<=1} onClick={()=>d.setPage(d.page-1)}>Sebelumnya</button><span>{d.page} / {d.pagination.totalPages || 1}</span><button type="button" className="app-button" disabled={d.loading||d.page>=d.pagination.totalPages} onClick={()=>d.setPage(d.page+1)}>Berikutnya</button></div>
 </section>;
}
