import React,{useState} from 'react';
import {NativeDialog} from '../../shared/components/common/NativeDialog';
import {outletValidationApi} from '../../services/api';
export function OutletReviewRequest({outlets,onClose,onSaved}) {
 const [reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(0),[run,setRun]=useState(false),[failures,setFailures]=useState([]),[completed,setCompleted]=useState([]);
 const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setProgress(completed.length);const done=[...completed],failed=[];try {
  const targets=failures.length?outlets.filter(o=>failures.some(f=>f.id===o.id)):outlets;
  for(const o of targets){try{const r=await outletValidationApi.openReview(o.id,{reason});if(run)await outletValidationApi.validateSingle(o.id,{reviewId:r.data.id,revision:r.data.revision});done.push(r.data);}catch(e){failed.push({id:o.id,name:o.name,error:e.message});}setProgress(p=>p+1);}
  setCompleted(done);setFailures(failed);if(!failed.length)await onSaved(done);
 }catch(e){setError(e.message);}finally{setBusy(false);}};
 return <NativeDialog open title="Ajukan pemeriksaan opsional" busy={busy} onClose={onClose}><form className="app-form" onSubmit={submit}><p>{outlets.length===1?outlets[0].name:`${outlets.length} outlet dipilih secara eksplisit`}</p><p className="outlet-muted">Gunakan untuk data lama atau data yang diragukan. Pemeriksaan tidak mengubah status aktif outlet.</p><label className="app-field">Alasan pemeriksaan<textarea required minLength={10} maxLength={1000} value={reason} disabled={completed.length>0} onChange={e=>setReason(e.target.value)} placeholder="Contoh: lokasi database lama perlu dicocokkan dengan data lapangan."/></label><label className="outlet-check"><input type="checkbox" checked={run} disabled={busy||failures.length>0} onChange={e=>setRun(e.target.checked)}/> Jalankan pemeriksaan peta untuk pilihan ini setelah kasus dibuka</label>{busy&&<p role="status">Memproses {Math.min(progress+1,outlets.length)} / {outlets.length} outlet… Hasil tiap outlet tersimpan.</p>}{error&&<p role="alert" className="app-error">{error}</p>}{failures.length>0&&<div className="app-error" role="alert"><p>{completed.length} selesai, {failures.length} perlu dicoba lagi.</p>{failures.map(f=><p key={f.id}>{f.name}: {f.error}</p>)}</div>}<div className="app-actions"><button type="button" className="app-button" disabled={busy} onClick={onClose}>Tutup</button><button type="submit" className="app-button app-button-primary" disabled={busy||!outlets.length}>{busy?'Memproses…':failures.length?'Ulangi outlet yang gagal':run?'Buka kasus & periksa peta':'Buka kasus pemeriksaan'}</button></div></form></NativeDialog>;
}
