import React,{useState} from 'react';
import {evidenceImageError} from '../../../../../shared/evidence-image-policy.mjs';
import {visitPurposes,collectionResults,includesCollection,validVisitAttachment,VISIT_ATTACHMENT_LIMIT} from '../../../../../shared/visit-outcome.mjs';
export function VisitOutcomeInput({value,onChange,allowCollection=true,required=false,policy={}}) {
 const [uploadError,setUploadError]=useState(''),[uploading,setUploading]=useState(false);
 const change=patch=>onChange({...value,...patch});
 const fieldRequired=['VISIT_RESULT_OFFER_MODE','VISIT_RESULT_OBSTACLE_MODE','VISIT_RESULT_ATTACHMENT_MODE'].some(k=>policy[k]==='REQUIRED');
 const attach=async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setUploadError('');if(files.length+(value.attachments?.length||0)>3){setUploadError('Maksimal 3 lampiran.');return;}setUploading(true);try{const added=[];for(const file of files){if(!['image/jpeg','image/png'].includes(file.type)||file.size>500*1024)throw new Error('Gunakan gambar JPEG/PNG maksimal 500 KB per file.');const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Gambar tidak dapat dibaca.'));reader.readAsDataURL(file);});if(dataUrl.length>VISIT_ATTACHMENT_LIMIT||!validVisitAttachment(dataUrl))throw new Error('Format atau ukuran gambar tidak valid.');const policyError=evidenceImageError(dataUrl,policy);if(policyError)throw new Error(policyError);added.push({name:file.name.slice(0,150),dataUrl});}change({attachments:[...(value.attachments||[]),...added]});}catch(error){setUploadError(error.message);}finally{setUploading(false);}};
 return <fieldset className="space-y-3 border rounded-xl p-3"><legend className="font-bold text-sm">Tujuan dan hasil kunjungan</legend>
  <label className="block text-sm">Tujuan<select className="form-input w-full" required={required||fieldRequired} value={value.purpose} onChange={e=>onChange({purpose:e.target.value})}><option value="">{required||fieldRequired?'Pilih tujuan (wajib)':'Pilih tujuan (opsional)'}</option>{Object.entries(visitPurposes).filter(([k])=>allowCollection||!includesCollection(k)).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
  {includesCollection(value.purpose)&&<>
   <label className="block text-sm">Referensi order / faktur sebelumnya<input className="form-input w-full" maxLength={500} value={value.reference||''} onChange={e=>change({reference:e.target.value})} placeholder="Nomor order atau faktur, termasuk dari luar aplikasi"/></label>
   <label className="block text-sm">Hasil penagihan<select className="form-input w-full" value={value.result||''} onChange={e=>{const rest={...value};delete rest.promiseDate;onChange({...rest,result:e.target.value});}}><option value="">Pilih hasil</option>{Object.entries(collectionResults).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
   {value.result==='PROMISED'&&<label className="block text-sm">Tanggal janji pembayaran<input className="form-input w-full" type="date" value={value.promiseDate||''} onChange={e=>change({promiseDate:e.target.value})}/></label>}
   <label className="block text-sm">Catatan hasil penagihan<textarea className="form-input w-full" maxLength={2000} value={value.note||''} onChange={e=>change({note:e.target.value})}/></label>
   <p className="text-xs">Pembayaran dilakukan di luar aplikasi. Hasil ini adalah laporan kunjungan sales; bukan verifikasi pelunasan.</p>
  </>}
  {value.purpose&&<>
   {!includesCollection(value.purpose)&&<label className="block text-sm">Catatan hasil kunjungan<textarea className="form-input w-full" maxLength={2000} required={policy.VISIT_RESULT_REQUIRE_NOTE} value={value.note||''} onChange={e=>change({note:e.target.value})}/></label>}
   {[['offer','VISIT_RESULT_OFFER_MODE','Rincian penawaran'],['obstacle','VISIT_RESULT_OBSTACLE_MODE','Kendala kunjungan']].map(([key,param,label])=>(policy[param]!=='DISABLED'||value[key])&&<label key={key} className="block text-sm">{label}{policy[param]==='REQUIRED'?' (wajib)':''}{policy[param]==='DISABLED'?<><p>Field dinonaktifkan. Hapus isinya sebelum mengirim.</p><button type="button" className="admin-button" onClick={()=>change({[key]:''})}>Hapus {label.toLowerCase()}</button></>:<textarea className="form-input w-full" maxLength={2000} required={policy[param]==='REQUIRED'} value={value[key]||''} onChange={e=>change({[key]:e.target.value})}/>}</label>)}
   {(policy.VISIT_RESULT_ATTACHMENT_MODE!=='DISABLED'||value.attachments?.length>0)&&<section><p className="text-sm">Lampiran hasil kunjungan{policy.VISIT_RESULT_ATTACHMENT_MODE==='REQUIRED'?' (wajib)':''}</p>{policy.VISIT_RESULT_ATTACHMENT_MODE!=='DISABLED'&&<label className="block text-sm">Tambahkan gambar JPEG/PNG, maksimal 3 file × 500 KB<input type="file" accept="image/jpeg,image/png" multiple disabled={uploading||(value.attachments?.length||0)>=3} onChange={attach}/></label>}{uploading&&<p role="status">Membaca gambar…</p>}{uploadError&&<p role="alert" className="app-error">{uploadError}</p>}<ul>{(value.attachments||[]).map((a,i)=><li key={i}>{a.name} <button type="button" className="admin-button" disabled={uploading} onClick={()=>change({attachments:value.attachments.filter((_,n)=>n!==i)})}>Hapus</button></li>)}</ul>{policy.VISIT_RESULT_ATTACHMENT_MODE==='DISABLED'&&<p>Hapus lampiran lama dari draft ini sebelum mengirim.</p>}</section>}
  </>}
 </fieldset>;
}
