import { prisma } from '../../../config/prisma.js';
import { AppError } from '../../../utils/errors.js';
import { assertSalesAccess } from '../../../utils/team-scope.js';
import { getDynamicConfig } from '../../config/config.service.js';
import { createNotification } from '../../notifications/notifications.service.js';
export const handleUnlockRequest = async (requestId,handlerId,approved) => {
  if (typeof approved !== 'boolean') throw new AppError('Keputusan persetujuan tidak valid',400);
  const handler = await prisma.user.findUnique({where:{id:handlerId}});
  if (!handler || !['ADMIN','SUPERVISOR'].includes(handler.role)) throw new AppError('Khusus admin/supervisor',403);
  const request = await prisma.outletUnlockRequest.findUnique({where:{id:requestId},include:{outlet:true}});
  if (!request) throw new AppError('Pengajuan tidak ditemukan',404);
  await assertSalesAccess(handler,request.requestedBy);
  if (handler.id === request.requestedBy) throw new AppError('Tidak boleh menyetujui pengajuan sendiri',403);
  const minutes = await getDynamicConfig('UNLOCK_VALIDITY_MINUTES',120);
  const expiresAt = approved ? new Date(Date.now()+minutes*60000) : null;
  const changed = await prisma.outletUnlockRequest.updateMany({where:{id:requestId,status:'PENDING_APPROVAL'},data:{status:approved?'APPROVED':'REJECTED',handledBy:handlerId,handledAt:new Date(),expiresAt}});
  if (!changed.count) throw new AppError('Pengajuan sudah diproses',409);
  const message = approved ? `Pengecualian untuk ${request.outlet.name} disetujui selama ${minutes} menit, khusus akun Anda.` : `Pengajuan pengecualian untuk ${request.outlet.name} ditolak.`;
  await createNotification(request.requestedBy,approved?'UNLOCK_APPROVED':'UNLOCK_REJECTED','Keputusan pengecualian absensi',message,{outletId:request.outletId,expiresAt});
  return {message,approved,expiresAt};
};
