import {calendarKey,calendarWorkingDay} from '../../../../../shared/report-calendar.mjs';
import {planDates} from '../../../../../shared/pjp-planning.mjs';
import {getDynamicConfig} from '../../config/config.service.js';
// Planning uses explicit dates; published PJP records are never regenerated by a calendar edit.
export async function planningCalendar(db,startsOn,endsOn,values){
 const source=values?.PJP_CALENDAR_SOURCE??await getDynamicConfig('PJP_CALENDAR_SOURCE','WEEKDAYS');
 if(source!=='REPORT_CALENDAR')return {source,missing:[],revisions:[]};
 const dates=planDates(startsOn,endsOn,366),months=[...new Set(dates.map(d=>d.slice(0,7)))];
 const rows=await db.systemConfig.findMany({where:{key:{in:months.map(calendarKey)}},select:{key:true,value:true}});
 const calendars=new Map(rows.filter(r=>r.value?.revision&&Array.isArray(r.value.weekdays)).map(r=>[r.value.month,r.value]));
 return {source,missing:months.filter(m=>!calendars.has(m)),workingDates:dates.filter(d=>calendarWorkingDay(calendars.get(d.slice(0,7)),d)===true),revisions:months.map(month=>({month,revision:calendars.get(month)?.revision??null}))};
}
