// Curated Belfoods master data, embedded explicitly for standalone seeding.
// Reviewed against the historical workbook; this module performs no file imports.
export const BELFOODS_FIXTURE = {
  "version": 1,
  "source": "BELFOODS_HISTORICAL_CALLPLAN",
  "outlets": [
    {
      "customer_id": "BFI2503508",
      "customer_name": "BORMA TOSERBA ANTAPANI",
      "address": "Jl. Terusan Jakarta No.53 Cicaheum Kiaracondong Kota Bandung Jawa Barat 40291 ",
      "latitude": -6.9126478,
      "longitude": 107.6492126,
      "geocode_confidence": "high",
      "catatan_validasi": "BORMA Toserba Antapani - exact match",
      "sales": "SLD539 YULI",
      "callplanId": "SLD534ALLWEEK",
      "day": 5,
      "sequence": 1,
      "sourceExcelRow": 30,
      "sourceExcelCallplanId": "SLD534ALLWEEK"
    },
    {
      "customer_id": "BFI2600617",
      "customer_name": "TRANSMART TSM BANDUNG",
      "address": "JL. GATOT SUBROTO NO.289, CIBANGKONG, KEC. BATUNUNGGAL, KOTA BANDUNG, JAWA BARAT 40273",
      "latitude": -6.9261732,
      "longitude": 107.6362126,
      "geocode_confidence": "high",
      "catatan_validasi": "Transmart TSM Bandung - exact match",
      "sales": "SLD539 YULI",
      "callplanId": "SLD534ALLWEEK",
      "day": 5,
      "sequence": 2,
      "sourceExcelRow": 31,
      "sourceExcelCallplanId": "SLD534ALLWEEK"
    },
    {
      "customer_id": "BFI7000709",
      "customer_name": "TOSERBA GRIYA DINASTI",
      "address": "JL KIARACONDONG NO 17 BLOK A2-A6 DAN B1 BANDUNG ",
      "latitude": -6.92204,
      "longitude": 107.644428,
      "geocode_confidence": "high",
      "catatan_validasi": "Toserba Griya Dinasty - exact match",
      "sales": "SLD539 YULI",
      "callplanId": "SLD534ALLWEEK",
      "day": 5,
      "sequence": 3,
      "sourceExcelRow": 32,
      "sourceExcelCallplanId": "SLD534ALLWEEK"
    },
    {
      "customer_id": "BFI7000715",
      "customer_name": "Borma Kiaracondong",
      "address": " Jl. Kiaracondong No.126 Binong Batununggal Kota Bandung Jawa Barat 40286 ",
      "latitude": -6.9427635,
      "longitude": 107.6412948,
      "geocode_confidence": "high",
      "catatan_validasi": "BORMA Toserba Kiaracondong - exact match",
      "sales": "SLD539 YULI",
      "callplanId": "SLD534ALLWEEK",
      "day": 5,
      "sequence": 4,
      "sourceExcelRow": 33,
      "sourceExcelCallplanId": "SLD534ALLWEEK"
    },
    {
      "customer_id": "BFI2500737",
      "customer_name": "NANAKAM FRESH",
      "address": "Jl. L. L. R.E. Martadinata No.20A Citarum Bandung Wetan - Kota Bandung ",
      "latitude": -6.9067911,
      "longitude": 107.614203,
      "geocode_confidence": "high",
      "catatan_validasi": "Nanakam Fresh Market - exact match",
      "sales": "SLD517 YATI",
      "callplanId": "SLD534ALLWEEK",
      "day": 5,
      "sequence": 1,
      "sourceExcelRow": 73,
      "sourceExcelCallplanId": "SLD517ALLWEEK"
    },
    {
      "customer_id": "BFI9002551",
      "customer_name": "YOGYA RIAU JUNCTION",
      "address": "JL LLRE MARTADINATA NO 17 BANDUNG ",
      "latitude": -6.90675,
      "longitude": 107.61236,
      "geocode_confidence": "high",
      "catatan_validasi": "Toserba Yogya Riau Junction - alamat No 17 cocok persis",
      "sales": "SLD517 YATI",
      "callplanId": "SLD534ALLWEEK",
      "day": 5,
      "sequence": 2,
      "sourceExcelRow": 74,
      "sourceExcelCallplanId": "SLD517ALLWEEK"
    },
    {
      "customer_id": "BFI7000708",
      "customer_name": "Grand Yogya Kepatihan",
      "address": "Jl. Kepatihan No.18, Balonggede, Regol Kota Bandung, Jawa Barat 40251 ",
      "latitude": -6.9234876,
      "longitude": 107.6056378,
      "geocode_confidence": "high",
      "catatan_validasi": "Grand Yogya Kepatihan - exact match",
      "sales": "SLD517 YATI",
      "callplanId": "SLD534ALLWEEK",
      "day": 4,
      "sequence": 1,
      "sourceExcelRow": 68,
      "sourceExcelCallplanId": "SLD517ALLWEEK"
    },
    {
      "customer_id": "BFI7000719",
      "customer_name": "BORMA DAGO",
      "address": "JL.IR H JUANDA NO 348  ",
      "latitude": -6.877073,
      "longitude": 107.6181504,
      "geocode_confidence": "high",
      "catatan_validasi": "BORMA Toserba Dago - exact match",
      "sales": "SLD517 YATI",
      "callplanId": "SLD534ALLWEEK",
      "day": 4,
      "sequence": 2,
      "sourceExcelRow": 69,
      "sourceExcelCallplanId": "SLD517ALLWEEK"
    },
    {
      "customer_id": "BFI1917914",
      "customer_name": "Pak Mustori",
      "address": "Komplek Jati Endah no.10 RT RW 05-011",
      "latitude": -6.9435229,
      "longitude": 107.6346648,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD516 (DADAN) W1",
      "callplanId": "SLD516W1",
      "day": 5,
      "sequence": 1,
      "sourceExcelRow": 130,
      "sourceExcelCallplanId": "SLD516W1"
    },
    {
      "customer_id": "BFI0900014",
      "customer_name": "Pd Berkah",
      "address": "JL. PASIR HONJE RT. 03-23 PASAR CICADAS BTM KEL. S",
      "latitude": -6.911284,
      "longitude": 107.644206,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD516 (DADAN) W1",
      "callplanId": "SLD516W1",
      "day": 5,
      "sequence": 2,
      "sourceExcelRow": 131,
      "sourceExcelCallplanId": "SLD516W1"
    },
    {
      "customer_id": "BFI1908863",
      "customer_name": "Pak Yadi",
      "address": "Jl marga asri v1-f blok c 188 rt-rw 006-008",
      "latitude": -6.9341624,
      "longitude": 107.5515652,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD516 (DADAN) W2",
      "callplanId": "SLD516W2",
      "day": 5,
      "sequence": 1,
      "sourceExcelRow": 190,
      "sourceExcelCallplanId": "SLD516W2"
    },
    {
      "customer_id": "BFI2308072",
      "customer_name": "Risky Jaya",
      "address": "jl.cigondewah rt06 -rw06 kp.cikeueus desa Rahayu M",
      "latitude": -6.9512312662297,
      "longitude": 107.5523088827,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD516 (DADAN) W2",
      "callplanId": "SLD516W2",
      "day": 5,
      "sequence": 2,
      "sourceExcelRow": 191,
      "sourceExcelCallplanId": "SLD516W2"
    },
    {
      "customer_id": "BFI2124239",
      "customer_name": "Indomart Cihampelas 122",
      "address": "JL.CIHAMPELAS NO 122",
      "latitude": -6.897423,
      "longitude": 107.6040933,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD515 { MT PURI}",
      "callplanId": "SLD515F4",
      "day": 5,
      "sequence": 1,
      "sourceExcelRow": 269,
      "sourceExcelCallplanId": "SLD515F4"
    },
    {
      "customer_id": "BFI2231499",
      "customer_name": "Indomaret Fresh Lembang",
      "address": "JL RAYA LEMBANG NO 307",
      "latitude": -6.81958547446,
      "longitude": 107.63223906378,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD515 { MT PURI}",
      "callplanId": "SLD515F4",
      "day": 5,
      "sequence": 2,
      "sourceExcelRow": 270,
      "sourceExcelCallplanId": "SLD515F4"
    },
    {
      "customer_id": "BFI2501010",
      "customer_name": "INDOMARET FRESH GUNUNG BATU",
      "address": "Sukaraja Cicendo Kota Bandung Jawa Barat",
      "latitude": -6.8898079,
      "longitude": 107.5699184,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD515 { MT PURI}",
      "callplanId": "SLD515F4",
      "day": 5,
      "sequence": 3,
      "sourceExcelRow": 271,
      "sourceExcelCallplanId": "SLD515F4"
    },
    {
      "customer_id": "BFI2507984",
      "customer_name": "INDOMARET FRESH DJUNJUNAN 166",
      "address": "JALAN DJUJUNAN NO 166.SUKAGALIH, KECAMATAN SUKAJADI,KOTA BANDUNG JAWA BARAT",
      "latitude": -6.8948453,
      "longitude": 107.5877974,
      "geocode_confidence": "high",
      "catatan_validasi": "Indomaret Fresh Djundjunan - exact match nama, alamat No 121 vs 166 (masih di jalan sama)",
      "sales": "SLD515 { MT PURI}",
      "callplanId": "SLD515F4",
      "day": 5,
      "sequence": 4,
      "sourceExcelRow": 272,
      "sourceExcelCallplanId": "SLD515F4"
    },
    {
      "customer_id": "BFI1901312",
      "customer_name": "Laris",
      "address": "Kp.bumi asih",
      "latitude": -6.9720371,
      "longitude": 107.5192267,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD514 (CAHYA) W1",
      "callplanId": "SLD514W1",
      "day": 5,
      "sequence": 1,
      "sourceExcelRow": 339,
      "sourceExcelCallplanId": "SLD514W1"
    },
    {
      "customer_id": "BFI1901390",
      "customer_name": "Opik",
      "address": "Jl Neglasari no.45 citape",
      "latitude": -6.93879,
      "longitude": 107.49688,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD514 (CAHYA) W1",
      "callplanId": "SLD514W1",
      "day": 5,
      "sequence": 2,
      "sourceExcelRow": 340,
      "sourceExcelCallplanId": "SLD514W1"
    },
    {
      "customer_id": "BFI2161364",
      "customer_name": "Toko Bcl",
      "address": "Jln.desa batujajar barat",
      "latitude": -6.9192579,
      "longitude": 107.4923636,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD514 (CAHYA) W2",
      "callplanId": "SLD514W2",
      "day": 5,
      "sequence": 1,
      "sourceExcelRow": 419,
      "sourceExcelCallplanId": "SLD514W2"
    },
    {
      "customer_id": "BFI2219466",
      "customer_name": "Rizki Irma",
      "address": "Kp cihurip rt 1 rw 12",
      "latitude": -6.9011169109156,
      "longitude": 107.44215457591,
      "geocode_confidence": null,
      "catatan_validasi": null,
      "sales": "SLD514 (CAHYA) W2",
      "callplanId": "SLD514W2",
      "day": 5,
      "sequence": 2,
      "sourceExcelRow": 420,
      "sourceExcelCallplanId": "SLD514W2"
    }
  ],
  "summary": {
    "sourceRows": 443,
    "uniqueOutletCodes": 443,
    "physicalSales": 5,
    "callplanVariants": 7
  },
  "sourceFiles": [
    {
      "path": "Analisis/KUNJUNGAN_TOKO_BELFOODS_CONVERTED.json",
      "bytes": 166927,
      "sha256": "0af995d344455d67e7b7a55c7c040068f0a0fc6ba157689d0d2cd986c6b03abe"
    },
    {
      "path": "Analisis/KUNJUNGAN_TOKO_BELFOODS_VALIDATED (1).xlsx",
      "bytes": 58307,
      "sha256": "d3ea976784ef274d60766657d389edad528c30a8083338c7793e8d9ab0869ee0"
    }
  ]
};
