import {useFeaturePolicy} from '../../../shared/hooks/useFeaturePolicy';
import {WarehouseRouteSummary} from '../../Warehouse/components/WarehouseRouteSummary';
import React,{useState} from 'react';
import {LuPlus,LuArrowLeft,LuSearch,LuRefreshCw} from 'react-icons/lu';
import {CreateRouteForm} from '../../Warehouse/components/CreateRouteForm';
import {RouteCard} from '../../Warehouse/components/DeliveryRouteCard';
import {RouteOperationsActions} from '../../Warehouse/components/RouteOperationsActions';
import {deliveryRouteLabel} from '../../Warehouse/deliveryLabels';
export function AdminRoutesWorkspace({role='ADMIN',routes,loading,error,page,total,setPage,showCreateForm,setShowCreateForm,fetchRoutes,handleStatusUpdate,handleDelete}){
  const featurePolicy=useFeaturePolicy('DELIVERY');
  const [selectedId,setSelectedId]=useState(null),[search,setSearch]=useState('');
  const selected=routes.find(route=>route.id===selectedId);
  const visible=routes.filter(route=>`${route.code} ${route.vehicle?.code||''} ${route.driver?.name||''}`.toLowerCase().includes(search.trim().toLowerCase()));
  return <div className="workspace-page admin-routes-workspace"><header className="admin-page-heading"><div><p className="admin-eyebrow">{role==='KEPALA_GUDANG'?'Gudang / Rencana trip':'Packing & pengiriman / Perencanaan'}</p><h1>{showCreateForm?'Buat rute pengiriman':selected?selected.code:role==='KEPALA_GUDANG'?'Rencana trip':'Rute & alokasi mobil'}</h1><p>{showCreateForm?'Tentukan kendaraan, driver, dan pembagian dokumen muatan.':'Susun perjalanan dan pastikan muatan sesuai kapasitas kendaraan.'}</p></div>{showCreateForm?<button type="button" className="admin-button" onClick={()=>{if(window.dispatchEvent(new CustomEvent('app:before-navigate',{cancelable:true})))setShowCreateForm(false);}}><LuArrowLeft/>Daftar rute</button>:selected?<button type="button" className="admin-button" onClick={()=>{if(window.dispatchEvent(new CustomEvent('app:before-navigate',{cancelable:true})))setSelectedId(null);}}><LuArrowLeft/>Daftar rute</button>:<div className="admin-heading-actions"><button className="admin-button" type="button" disabled={loading} onClick={fetchRoutes}><LuRefreshCw/>Perbarui</button><button className="admin-button primary" type="button" disabled={!!error||!featurePolicy.canStart} title={featurePolicy.reason} onClick={()=>setShowCreateForm(true)}><LuPlus/>Buat rute</button></div>}</header>
    {error&&<p className="admin-feedback error" role="alert">{error}</p>}
    {showCreateForm?<CreateRouteForm onCreated={()=>{setShowCreateForm(false);fetchRoutes();}} onCancel={()=>setShowCreateForm(false)}/>:selected?<section className="admin-route-document"><fieldset disabled={!!error}>{role==='KEPALA_GUDANG'?<WarehouseRouteSummary route={selected} onDelete={handleDelete}/>:<RouteCard route={selected} onStatusUpdate={handleStatusUpdate} onDelete={handleDelete}/>}<div className="admin-panel p-5 mt-4"><h2 className="font-semibold mb-4">Tindakan perjalanan</h2><RouteOperationsActions key={selected.id} route={selected} onChanged={fetchRoutes}/></div></fieldset></section>:<><div className="admin-toolbar"><label className="admin-search"><LuSearch aria-hidden="true"/><input type="search" aria-label="Cari rute di halaman ini" placeholder="Cari trip, kendaraan, atau driver di halaman ini…" value={search} onChange={event=>setSearch(event.target.value)}/></label><span className="admin-footnote">{total} rute terdaftar</span></div><section className="admin-panel"><div className="admin-table-scroll"><table className="admin-data-table"><caption className="sr-only">Rute dan alokasi kendaraan</caption><thead><tr><th>Rute / tanggal</th><th>Kendaraan</th><th>Driver</th><th>Muatan</th><th>Tujuan</th><th>Status</th></tr></thead><tbody>{visible.map(route=><tr key={route.id}><td><button type="button" className="admin-table-link" onClick={()=>setSelectedId(route.id)}><strong>{route.code}</strong><span>{route.date?new Date(route.date).toLocaleDateString('id-ID',{timeZone:'Asia/Jakarta'}):'Belum terjadwal'}</span></button></td><td>{route.vehicle?.code||route.vehicle?.name||'Belum ditetapkan'}</td><td>{route.driver?.name||'Belum ditetapkan'}</td><td>{route.totalCartons||0} karton</td><td>{route.stops?.length||0} outlet</td><td><span className="admin-status">{deliveryRouteLabel(route)}</span></td></tr>)}</tbody></table>{!visible.length&&<p className="admin-empty">{loading?'Memuat rute…':'Tidak ada rute dalam pilihan ini.'}</p>}</div><footer className="admin-pagination"><span>Halaman {page} / {Math.max(1,Math.ceil(total/20))} · {total} rute</span><div><button disabled={page===1||loading} type="button" onClick={()=>setPage(page-1)}>Sebelumnya</button><button disabled={page*20>=total||loading} type="button" onClick={()=>setPage(page+1)}>Berikutnya</button></div></footer></section></>}
  </div>;
}
