import {useFeaturePolicy} from '../../../shared/hooks/useFeaturePolicy';
import React,{useState} from 'react';
import {LuPlus,LuRefreshCw,LuSearch,LuArrowLeft} from 'react-icons/lu';
import {PackingDraftForm} from '../../Warehouse/components/PackingDraftForm';
import {PackingListCard} from '../../Warehouse/components/PackingListCard';
import {PackingListPrintModal} from '../../Warehouse/components/PackingListPrintModal';
import {AdminPackingOrderPicker} from './AdminPackingOrderPicker';
import {OrderFulfillmentPanel} from '../../Warehouse/components/OrderFulfillmentPanel';
import {NativeDialog} from '../../../shared/components/common/NativeDialog';
import {AdminPackingTable} from './AdminPackingTable';
export function AdminPackingWorkspace(props){
  const featurePolicy=useFeaturePolicy('PACKING');
  const {busyAction,confirmDialog,error,expandedId,form,loading,metrics,page,printDoc,refresh,result,search,setConfirmDialog,setForm,setPage,setPrintDoc,setSearch,setStatus,setSuccess,settings,status,success,toggleExpand}=props;
  const [sourceOpen,setSourceOpen]=useState(false),[sourceTab,setSourceTab]=useState('orders');
  const selected=result.items.find(item=>item.id===expandedId);
  const selectOrder=order=>{setSourceOpen(false);setForm({order});};
  const heading=<header className="admin-page-heading"><div><p className="admin-eyebrow">Packing & pengiriman / Dokumen</p><h1>{form?form.document?'Revisi packing list':'Buat packing list':selected?selected.code:'Packing list'}</h1><p>{form?'Lengkapi barang, kemasan, dan faktur dalam satu dokumen.':selected?'Periksa rincian, kelengkapan, dan riwayat dokumen.':'Siapkan dokumen muatan sebelum diserahkan ke kepala gudang.'}</p></div>{!form&&!selected&&<div className="admin-heading-actions"><button type="button" className="admin-button" disabled={loading} onClick={refresh}><LuRefreshCw/>Perbarui</button><button type="button" className="admin-button primary" disabled={!featurePolicy.canStart} title={featurePolicy.reason} onClick={()=>setSourceOpen(true)}><LuPlus/>Buat packing list</button></div>}{selected&&!form&&<button type="button" className="admin-button" onClick={()=>toggleExpand(selected.id)}><LuArrowLeft/>Daftar packing</button>}</header>;
  if(form)return <div className="workspace-page admin-packing-editor">{heading}<PackingDraftForm key={form.document?.id||form.order?.id||'manual'} {...form} onSaved={message=>{setForm(null);setSuccess(message);refresh();}} onCancel={()=>setForm(null)}/></div>;
  return <div className="workspace-page admin-packing-workspace">{heading}
    {error&&<p className="admin-feedback error" role="alert">{error}</p>}{success&&<p className="admin-feedback success" role="status">{success}</p>}
    {selected?<div className="admin-packing-document"><PackingListCard {...props} pl={selected} onChanged={refresh} isDraft={selected.status==='DRAFT'} isReleased={selected.status==='RELEASED'} isAllocated={Boolean(selected.deliveryStops?.length)} needsCompletion={selected.status==='DRAFT'&&(!selected.totalCartons||!selected.invoices?.length)} isExpanded isReleaseBusy={busyAction===`${selected.id}_RELEASE`} isRecallBusy={busyAction===`${selected.id}_RECALL`} isDeleteBusy={busyAction===`${selected.id}_DELETE`}/></div>:<>
      <div className="admin-inline-metrics"><span><strong>{metrics.total}</strong> dokumen</span><span><strong>{metrics.draftCount}</strong> draft</span><span><strong>{metrics.releasedCount}</strong> dikirim ke gudang</span><span><strong>{metrics.incompleteCount}</strong> perlu dilengkapi</span></div>
      <div className="admin-toolbar"><label className="admin-search"><LuSearch aria-hidden="true"/><input type="search" aria-label="Cari packing list" placeholder="Cari kode atau nama outlet…" value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}}/></label><label className="admin-select-label">Status<select value={status} onChange={event=>{setStatus(event.target.value);setPage(1);}}><option value="">Semua status</option><option value="DRAFT">Draft admin</option><option value="RELEASED">Dikirim ke gudang</option></select></label></div>
      <section className="admin-panel"><AdminPackingTable items={result.items} loading={loading} onSelect={toggleExpand}/><footer className="admin-pagination"><span>{result.total} dokumen · Halaman {page} / {Math.max(1,Math.ceil(result.total/20))}</span><div><button type="button" disabled={page===1||loading} onClick={()=>setPage(page-1)}>Sebelumnya</button><button type="button" disabled={page*20>=result.total||loading} onClick={()=>setPage(page+1)}>Berikutnya</button></div></footer></section>
      <p className="admin-footnote">{settings?.PACKING_AUTO_RELEASE?'Dokumen lengkap otomatis dikirim ke gudang setelah disimpan.':'Dokumen disimpan sebagai draft; kirim ke gudang setelah lengkap.'}</p>
    </>}
    <NativeDialog open={sourceOpen} title="Pilih sumber packing list" onClose={()=>setSourceOpen(false)} className="admin-source-dialog"><p className="admin-dialog-description">Pilih order yang akan dipenuhi. Rincian barang mengikuti sisa order yang belum dipacking.</p><nav className="admin-local-tabs" aria-label="Sumber packing"><button type="button" aria-pressed={sourceTab==='orders'} onClick={()=>setSourceTab('orders')}>Pilih order</button><button type="button" aria-pressed={sourceTab==='remaining'} onClick={()=>setSourceTab('remaining')}>Sisa pemenuhan</button></nav>{sourceTab==='orders'?<AdminPackingOrderPicker allowPending={settings?.PACKING_ALLOW_PENDING_ORDER} onSelect={selectOrder}/>:<OrderFulfillmentPanel onSelect={selectOrder}/>} {settings?.PACKING_SOURCE_MODE!=='ORDER'&&<div className="admin-dialog-actions"><button type="button" onClick={()=>{setSourceOpen(false);setForm({});}}>Buat draft manual</button></div>}</NativeDialog>
    <NativeDialog open={Boolean(confirmDialog)} title={confirmDialog?.title||'Konfirmasi tindakan'} onClose={()=>setConfirmDialog(null)} busy={Boolean(busyAction)}><p>{confirmDialog?.message}</p><div className="admin-dialog-actions"><button type="button" onClick={()=>setConfirmDialog(null)}>Batal</button><button type="button" className="admin-primary-button" onClick={confirmDialog?.onConfirm} disabled={Boolean(busyAction)}>Lanjutkan</button></div></NativeDialog>
    <PackingListPrintModal document={printDoc} onClose={()=>setPrintDoc(null)}/>
  </div>;
}
