import React,{useState} from 'react';
export const planStatusLabel=status=>({DRAFT:'Draft',SCHEDULED:'Penerbitan terjadwal',PUBLISHED:'Diterbitkan',CANCELLED:'Sisa agenda dibatalkan'}[status]||status);
export function PlanPublicationStatus({planner:p}){
 const [note,setNote]=useState('');
 const schedule=p.value.publicationSchedule;
 const cancelled=p.value.history?.findLast(h=>h.action==='CANCEL_PUBLISHED');
 if(p.value.status==='CANCELLED')return <section className="admin-panel planner-panel-body"><h3>Riwayat pembatalan</h3><p>{cancelled?.note}</p><p>{cancelled?.cancelled.length||0} agenda dibatalkan. {cancelled?.retained.length||0} agenda dipertahankan karena lampau atau beraktivitas.</p>{cancelled?.retained.map(v=><p key={v.id}>{v.code||v.id} · {v.date} · {v.reason}</p>)}</section>;
 if(p.value.status==='PUBLISHED'&&p.planPolicy.PJP_ALLOW_CANCEL_PUBLISHED!==false)return <section className="admin-panel planner-panel-body"><h3>Batalkan sisa agenda tanpa aktivitas</h3><p>Hanya agenda hari ini/masa depan yang belum memiliki aktivitas akan dibatalkan. Presensi, hasil, order, perubahan rute dan agenda lampau dilindungi. Rincian agenda batal tetap berada dalam riwayat rencana.</p><label className="app-field">Alasan pembatalan<textarea minLength={5} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><button type="button" className="admin-button" disabled={p.busy||note.trim().length<5} onClick={()=>{if(window.confirm('Batalkan sisa agenda yang belum memiliki aktivitas?'))p.cancelPublished({note});}}>Batalkan sisa agenda</button></section>;
 if(p.value.status!=='SCHEDULED'&&schedule?.state!=='FAILED')return null;
 if(schedule?.state==='FAILED')return <section role="alert" className="admin-feedback error"><strong>Penerbitan belum berhasil</strong><p>{schedule.failure}</p><p>Draft dapat diperbaiki. Simpan dan tinjau kalender sebelum menjadwalkan kembali.</p></section>;
 return <section className="admin-panel planner-panel-body"><h3>Penerbitan terjadwal</h3><p>{new Date(p.value.scheduledAt).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</p><p>Belum ada PJP dari jadwal ini. Draft dikunci sampai jadwal dibatalkan atau diproses. Jika fitur PJP dijeda, penerbitan menunggu sampai aktif kembali.</p><label className="app-field">Alasan pembatalan jadwal<textarea value={note} minLength={5} maxLength={1000} onChange={e=>setNote(e.target.value)} placeholder="Contoh: Ada perubahan penugasan tim yang perlu diperiksa."/></label><div className="app-actions"><button type="button" className="admin-button" disabled={p.busy||note.trim().length<5} onClick={()=>p.cancelSchedule({note})}>Batalkan jadwal dan buka draft</button><button type="button" className="admin-button" disabled={p.busy} onClick={()=>p.choose(p.value.id)}>Perbarui status</button></div></section>;
}
