import React,{useState} from 'react';
import {manualCodeRequired} from '../../../../../../shared/coding.mjs';
import {wibDateKey} from '../../../../../../shared/visit-metrics.mjs';
import {useApp} from '../../../../context/AppContext';
export function PlanCalendarReview({planner:p}){
 const {settings}=useApp(),[person,setPerson]=useState(''),[note,setNote]=useState(''),[ack,setAck]=useState(false),[codes,setCodes]=useState({}),[scheduledAt,setScheduledAt]=useState('');
 const r=p.review,manual=manualCodeRequired('PJP',settings);
 if(!r)return <section className="admin-panel planner-review-empty"><h2>Kalender dan pemeriksaan</h2><p>Setelah menyusun aturan, pilih “Tinjau kalender” untuk melihat tanggal kunjungan, benturan, dan cakupan outlet.</p></section>;
 const people=r.context.sales,selected=people.some(s=>s.id===person)?person:people[0]?.id,days=r.days.filter(d=>d.userId===selected),hasWarnings=!!(r.warnings.length||r.uncovered.length),existing=r.existing.filter(e=>r.days.some(d=>d.userId===e.userId&&d.date===wibDateKey(e.date)&&d.outletIds.length));
 return <section className="admin-panel planner-calendar"><div className="admin-panel-heading"><div><h2>Tinjau sebelum diterbitkan</h2><p>{r.summary.visits} kunjungan · {r.summary.covered} outlet dalam aturan · {r.summary.uncovered} belum terencana</p></div></div><div className="planner-panel-body">
  <p className="app-notice">Kalender: {r.calendar?.source==='REPORT_CALENDAR'?'kalender bulanan Admin, termasuk pengecualian tanggal':'hari kerja mingguan PJP'}. Perubahan kalender tidak mengubah PJP yang sudah terbit.</p>
  {!!r.problems.length&&<div role="alert" className="admin-feedback error"><strong>{r.problems.length} masalah perlu diperbaiki</strong><ul>{r.problems.map((v,i)=><li key={i}>{v.message}</li>)}</ul></div>}
  {!!existing.length&&<p role="alert" className="admin-feedback error">{existing.length} PJP sudah terbit pada tanggal yang beririsan. Ubah periode atau aturan; perubahan PJP berjalan dilakukan melalui tindak lanjut rute.</p>}
  {!!r.warnings.length&&<div className="app-notice"><ul>{r.warnings.map((v,i)=><li key={i}>{v.message}</li>)}</ul></div>}
  {!!r.uncovered.length&&<details className="planner-uncovered"><summary>{r.uncovered.length} outlet tim belum memiliki aturan</summary><ul>{r.uncovered.map(o=><li key={o.id}>{o.name} · {o.clusterName}</li>)}</ul></details>}
  <label className="app-field">Kalender Sales<select value={selected||''} onChange={e=>setPerson(e.target.value)}>{people.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><ol className="planner-calendar-days">{days.map(d=><li key={d.date}><div><strong>{new Date(`${d.date}T05:00:00Z`).toLocaleDateString('id-ID',{weekday:'short',day:'numeric',month:'short'})}</strong><span>{d.outletIds.length?`${d.outletIds.length} kunjungan`:d.state==='NOT_DUE'?'Tidak jatuh tempo':'Belum disusun'}</span></div>{!!d.outletIds.length&&<ol>{d.outletIds.map(id=><li key={id}>{r.context.outlets.find(o=>o.id===id)?.name||id}</li>)}</ol>}</li>)}</ol>
  {p.value.status==='DRAFT'&&<fieldset disabled={p.busy||!p.canStart}><h3>Penerbitan PJP</h3><p className="admin-footnote">PJP diterbitkan hanya pada tanggal yang memiliki kunjungan. Jadwal ini akan langsung terlihat oleh Sales pada tanggal penugasan.</p>{manual&&r.days.filter(d=>d.outletIds.length).map(d=><label key={`${d.userId}:${d.date}`} className="app-field">Kode PJP · {d.salesName} · {d.date}<input value={codes[`${d.userId}:${d.date}`]||''} maxLength={128} onChange={e=>setCodes(v=>({...v,[`${d.userId}:${d.date}`]:e.target.value}))}/></label>)}<label className="app-field">Catatan penerbitan<textarea minLength={5} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Contoh: Rencana kunjungan tim untuk periode ini sudah diperiksa."/></label>{hasWarnings&&<label className="planner-check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Saya sudah meninjau outlet yang belum terencana dan penyesuaian interval.</label>}{r.context.policy?.values.PJP_ALLOW_SCHEDULED_PUBLISH!==false&&<label className="app-field">Waktu penerbitan (WIB, opsional)<input type="datetime-local" value={scheduledAt} max={`${p.value.startsOn}T23:59`} onChange={e=>setScheduledAt(e.target.value)}/><span className="admin-footnote">Kosongkan untuk terbit sekarang. Jadwal tersimpan di server; rencana diperiksa ulang saat penerbitan.</span></label>}<button type="button" className="admin-button primary" title={p.featureReason} disabled={!p.canStart||p.dirty||!p.value.id||!!r.problems.length||!!existing.length||!r.summary.visits||note.trim().length<5||(hasWarnings&&!ack)} onClick={()=>scheduledAt?p.schedule({note,codes,acknowledgeWarnings:ack,scheduledAt:new Date(`${scheduledAt}:00+07:00`).toISOString()}):p.publish({note,codes,acknowledgeWarnings:ack})}>{scheduledAt?'Jadwalkan penerbitan':'Terbitkan'} {r.days.filter(d=>d.outletIds.length).length} PJP</button>{(p.dirty||!p.value.id)&&<p className="admin-footnote">Simpan draft terlebih dahulu, lalu tinjau kalender sekali lagi.</p>}</fieldset>}
 </div></section>;
}
