import React from 'react';
import {useVisitPlanner} from '../../hooks/useVisitPlanner';
import {PlanRuleEditor} from './PlanRuleEditor';
import {PlanCalendarReview} from './PlanCalendarReview';
import {PlanPublicationStatus,planStatusLabel} from './PlanPublicationStatus';
export function VisitPlanner(){
 const p=useVisitPlanner(),locked=p.busy||p.loading||p.value.status!=='DRAFT'||!p.canStart;
 return <section className="visit-planner"><div className="planner-intro"><div><h2>Planner kunjungan</h2><p>Susun wilayah kunjungan menjadi tanggal kerja, periksa hasilnya, lalu terbitkan PJP.</p></div><div className="app-actions">{!!p.value.rules.length&&<button type="button" className="admin-button" disabled={p.busy||p.loading||!p.canStart} title={p.featureReason} onClick={p.copyNext}>Salin ke periode berikutnya</button>}<button type="button" className="admin-button" disabled={p.busy||p.loading||!p.canStart} title={p.featureReason} onClick={()=>p.choose('')}>Rencana baru</button></div></div>
  {p.error&&<p role="alert" className="admin-feedback error">{p.error}<button type="button" className="admin-button" disabled={p.busy||p.loading} onClick={p.reload}>Muat ulang sumber data</button></p>}{p.message&&<p role="status" className="admin-feedback">{p.message}</p>}{(p.restored||p.policyChanged)&&<p className="app-notice">{p.restoreMessage} Muat rencana tersimpan untuk mengambil revisi terbaru dari server.</p>}{p.storageError&&<p role="alert" className="app-error">{p.storageError}</p>}
  <label className="app-field">Rencana tersimpan<select value={p.plans.some(v=>v.id===p.value.id)?p.value.id:''} disabled={p.busy} onChange={e=>p.choose(e.target.value)}><option value="">Draft baru / lokal</option>{p.plans.map(v=><option key={v.id} value={v.id}>{v.name} · {v.startsOn}–{v.endsOn} · {planStatusLabel(v.status)} · revisi {v.revision}</option>)}</select></label>
  <section className="admin-panel planner-panel-body"><div className="planner-status-line"><strong>{planStatusLabel(p.value.status)}</strong><span>{p.value.id?`Revisi ${p.value.revision}`:'Belum tersimpan di server'}</span></div><fieldset disabled={locked} className="planner-settings"><label className="app-field">Nama rencana<input minLength={3} maxLength={150} value={p.value.name} onChange={e=>p.field('name',e.target.value)}/></label><label className="app-field">Tim Supervisor<select value={p.value.supervisorId} disabled={!!p.value.id} onChange={e=>{if(p.value.rules.length&&!window.confirm('Ganti tim dan kosongkan aturan pada draft ini?'))return;p.changeTeam(e.target.value);}}><option value="">Pilih tim</option>{p.team.supervisors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="app-field">Mulai periode<input type="date" value={p.value.startsOn} onChange={e=>p.field('startsOn',e.target.value)}/></label><label className="app-field">Akhir periode<input type="date" value={p.value.endsOn} min={p.value.startsOn} onChange={e=>p.field('endsOn',e.target.value)}/></label></fieldset><p className="admin-footnote">Periode maksimal {p.maxPlanDays} hari. F1/F2/F4 berarti setiap 1/2/4 minggu sejak tanggal acuan; pergantian bulan tidak mengulang siklus.</p></section>
  <PlanPublicationStatus planner={p}/>
  {p.loading?<p role="status">Memuat tim, wilayah, dan rencana…</p>:<div className="planner-columns"><PlanRuleEditor planner={p}/><PlanCalendarReview key={`${p.value.id}:${p.value.revision}`} planner={p}/></div>}
  <div className="planner-footer"><span>{p.value.rules.length} aturan · {p.dirty?'Perubahan belum disimpan':'Draft sesuai salinan yang dimuat'}</span><div className="app-actions"><button type="button" className="admin-button" disabled={locked||!p.value.supervisorId} onClick={p.save}>Simpan draft</button><button type="button" className="admin-button primary" disabled={p.busy||p.loading||!p.value.supervisorId} onClick={p.preview}>{p.busy?'Memproses…':'Tinjau kalender'}</button></div></div>
  {!!p.value.history?.length&&<details className="planner-history"><summary>Riwayat rencana</summary>{p.value.history.map((h,i)=><p key={i}>{new Date(h.at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} · {({PUBLISH:'Diterbitkan',CREATE:'Draft dibuat',UPDATE:'Draft diperbarui',SCHEDULE:'Penerbitan dijadwalkan',CANCEL_SCHEDULE:'Jadwal dibatalkan',CANCEL_PUBLISHED:'Sisa agenda dibatalkan',SCHEDULE_FAILED:'Penerbitan gagal'})[h.action]||h.action} · {h.note}</p>)}</details>}
 </section>;
}
