import React, { useEffect, useState } from 'react';
import { LuPlus, LuX, LuArrowRight } from 'react-icons/lu';
import DeliveryTabs from './DeliveryTabs';

export default function RouteWorkspace({ documents, go, notify, initialView, saveView }) {
  const [allocated, setAllocated] = useState(initialView.allocated || []);
  const [vehicle, setVehicle] = useState(initialView.vehicle || 'D 8124 AB · 120 karton');
  const [driver, setDriver] = useState(initialView.driver || 'Dedi Kurniawan');
  const [departure, setDeparture] = useState(initialView.departure || '2026-10-09T08:00');
  const [saved, setSaved] = useState(initialView.saved || false);
  useEffect(() => saveView({ allocated, vehicle, driver, departure, saved }), [allocated, vehicle, driver, departure, saved, saveView]);
  const available = documents.filter(d => d.status === 'Dirilis' && !allocated.includes(d.id));
  const chosen = allocated.map(id => documents.find(d => d.id === id));
  const cartons = chosen.reduce((sum, d) => sum + Number(d.cartons), 0);
  return <main id="workspace" className="module-workspace"><div className="page-heading"><div><p className="eyebrow">LOGISTIK</p><h1>Rute & alokasi</h1><p>Susun muatan, kendaraan, driver, dan urutan outlet dalam satu tempat.</p></div></div><DeliveryTabs page="routes" go={go} />
    <div className="route-grid"><section className="list-panel"><div className="panel-heading"><h2>Muatan siap dialokasikan</h2><span>{available.length} dokumen</span></div>{available.map(d => <div className="allocation-row" key={d.id}><div><strong>{d.id}</strong><span>{d.outlet}</span><small>{d.cartons} karton</small></div><button className="secondary" onClick={() => { setAllocated([...allocated, d.id]); setSaved(false); }}><LuPlus />Alokasikan</button></div>)}{!available.length && <div className="empty-state"><p>Semua dokumen siap telah dialokasikan.</p></div>}</section><section className="route-composer"><div className="panel-heading"><h2>Susunan perjalanan</h2><span>Draft</span></div><div className="route-fields"><label>Kendaraan<select value={vehicle} onChange={e => { setVehicle(e.target.value); setSaved(false); }}><option>D 8124 AB · 120 karton</option><option>D 9032 CD · 120 karton</option></select></label><label>Driver<select value={driver} onChange={e => { setDriver(e.target.value); setSaved(false); }}><option>Dedi Kurniawan</option><option>Asep Hidayat</option></select></label><label>Rencana berangkat<input type="datetime-local" value={departure} onChange={e => { setDeparture(e.target.value); setSaved(false); }} /></label></div><div className={`capacity-bar ${cartons > 120 ? 'over-capacity' : ''}`}><span><strong>{cartons} / 120 karton</strong><small>{cartons > 120 ? 'Melebihi kapasitas kendaraan' : 'Kapasitas contoh kendaraan'}</small></span><progress value={Math.min(cartons, 120)} max="120" /></div><h3 className="route-stop-label">Urutan outlet</h3>{chosen.map((d, index) => <div className="allocation-row" key={d.id}><span className="stop-index">{index + 1}</span><div><strong>{d.outlet}</strong><small>{d.id} · {d.cartons} karton</small></div><div className="button-row"><button className="text-button" disabled={!index} onClick={() => { const copy = [...allocated]; [copy[index - 1], copy[index]] = [copy[index], copy[index - 1]]; setAllocated(copy); setSaved(false); }}>Naik</button><button className="icon-button" aria-label={`Hapus alokasi ${d.id}`} onClick={() => { setAllocated(allocated.filter(id => id !== d.id)); setSaved(false); }}><LuX /></button></div></div>)}{!chosen.length && <div className="empty-state"><p>Pilih muatan dari antrean di sebelah kiri.</p></div>}<div className="composer-actions"><button className="primary" disabled={!chosen.length || cartons > 120 || !departure} onClick={() => { setSaved(true); notify('Susunan perjalanan contoh disimpan untuk sesi pratinjau ini.'); }}>{saved ? 'Tersimpan pada pratinjau' : 'Simpan susunan contoh'}</button><button className="text-button" onClick={() => go('monitor')}>Monitor perjalanan<LuArrowRight /></button></div></section></div></main>;
}
