import {Router} from 'express';
import {authorize} from '../../middlewares/auth.middleware.js';
import {getPolicyProfile,savePolicyDraft,previewPolicy,publishPolicy,restorePolicy,cancelScheduledPolicy} from './services/policy-profiles.service.js';
import {policyOptions,simulatePolicy} from './services/policy-simulation.service.js';
import {notificationDeliveryStatus,retryNotificationDelivery} from '../notifications/services/notification-delivery.service.js';
const router=Router();
router.use(authorize('ADMIN'));
const run=fn=>async(req,res,next)=>{try{res.set('Cache-Control','no-store').json({data:await fn(req)});}catch(error){next(error);}};
router.get('/',run(req=>getPolicyProfile(req.query.scope||'GLOBAL')));
router.get('/options',run(()=>policyOptions()));
router.get('/notification-delivery',run(()=>notificationDeliveryStatus()));
router.post('/notification-delivery/retry',run(req=>retryNotificationDelivery(req.body,req.user)));
router.post('/simulate',run(req=>simulatePolicy(req.body.scope||'GLOBAL',req.body)));
router.put('/draft',run(req=>savePolicyDraft(req.body.scope||'GLOBAL',req.body,req.user)));
router.post('/preview',run(req=>previewPolicy(req.body.scope||'GLOBAL',req.body.revision)));
router.post('/publish',run(req=>publishPolicy(req.body.scope||'GLOBAL',req.body,req.user)));
router.post('/restore',run(req=>restorePolicy(req.body.scope||'GLOBAL',req.body,req.user)));
router.post('/cancel-schedule',run(req=>cancelScheduledPolicy(req.body.scope||'GLOBAL',req.body,req.user)));
export default router;
