ALTER TABLE "OffPjpAttendance" ADD COLUMN IF NOT EXISTS "orderAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "OffPjpAttendance" ADD COLUMN IF NOT EXISTS "skuSold" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OffPjpAttendance" ADD COLUMN IF NOT EXISTS "salesProducts" JSONB;
ALTER TABLE "OffPjpAttendance" ADD COLUMN IF NOT EXISTS "isEffectiveCall" BOOLEAN NOT NULL DEFAULT false;
