import React,{useEffect,useState} from 'react';
import {configApi} from '../../services/api';
import {ASSIGNMENT_KINDS,ASSIGNMENT_STATES,wibInputToIso} from '../../../../shared/assignment-schedules.mjs';
const stamp=value=>value?new Date(value).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})+' WIB':'Permanen';
export function AssignmentScheduleCenter(){
 const [kind,setKind]=useState('FOLLOW_UP'),[options,setOptions]=useState(null),[rows,setRows]=useState([]),[taskId,setTaskId]=useState(''),[ownerId,setOwnerId]=useState(''),[startsAt,setStartsAt]=useState(''),[endsAt,setEndsAt]=useState(''),[dueAt,setDueAt]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{const [a,b]=await Promise.all([configApi.assignmentScheduleOptions(kind),configApi.assignmentSchedules()]);setOptions(a.data);setRows(b.data);};
 useEffect(()=>{let active=true;setOptions(null);setTaskId('');setOwnerId('');setEndsAt('');setDueAt('');setError('');Promise.all([configApi.assignmentScheduleOptions(kind),configApi.assignmentSchedules()]).then(([a,b])=>{if(active){setOptions(a.data);setRows(b.data);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[kind]);
 const task=options?.tasks.find(row=>row.id===taskId);
 const submit=async e=>{e.preventDefault();if(!task||busy)return;setBusy(true);setError('');setMessage('');try{await configApi.scheduleAssignment({kind,entityId:task.id,fingerprint:task.fingerprint,ownerId,startsAt:wibInputToIso(startsAt),endsAt:kind==='TEAM'?null:wibInputToIso(endsAt),dueAt:kind==='TEAM'?null:kind==='FOLLOW_UP'?dueAt:wibInputToIso(dueAt),reason});await load();setMessage('Jadwal tersimpan. Sistem memeriksa ulang kelayakan pada waktu mulai.');setReason('');}catch(e){setError(e.message);}finally{setBusy(false);}};
 const change=async(row,retry)=>{if(reason.trim().length<5){setError('Isi alasan minimal lima karakter sebelum membatalkan atau mengulang jadwal.');return;}setBusy(true);setError('');try{if(retry)await configApi.retryAssignmentSchedule(row.id,reason);else await configApi.cancelAssignmentSchedule(row.id,reason);await load();setMessage(retry?'Jadwal dimasukkan kembali untuk diperiksa.':'Jadwal dibatalkan.');}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <details className="policy-panel"><summary className="p-4 font-semibold cursor-pointer">Penugasan bertanggal & delegasi sementara</summary><div className="policy-panel-body space-y-4">
  <p>Jadwalkan pengganti tanpa menambah hak aksesnya. Akhir delegasi memulihkan PIC awal jika tugas belum dikirim/selesai dan penugasan belum berubah. Waktu mengikuti WIB.</p>
  {error&&<p role="alert" className="app-error">{error}</p>}{message&&<p role="status">{message}</p>}
  {kind==='TEAM'&&<p className="policy-note">Transfer tim berlaku permanen pada waktu mulai. PJP dan bukti yang sudah terbentuk dipertahankan; penugasan wilayah lama yang berbeda tim dilepas dan template jadwal mendatang perlu dibuat kembali.</p>}
  <form onSubmit={submit} className="grid gap-4"><fieldset disabled={busy} className="grid gap-4 md:grid-cols-2">
   <label className="policy-field">Proses<select className="config-input" value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(ASSIGNMENT_KINDS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
   <label className="policy-field">Pekerjaan terbuka<select required className="config-input" value={taskId} onChange={e=>{setTaskId(e.target.value);setOwnerId('');setDueAt('');}}><option value="">Pilih pekerjaan</option>{options?.tasks.map(row=><option key={row.id} value={row.id}>{row.label}</option>)}</select></label>
   <label className="policy-field">Petugas pengganti<select required className="config-input" value={ownerId} onChange={e=>setOwnerId(e.target.value)}><option value="">Pilih petugas</option>{options?.people.filter(p=>p.id!==task?.ownerId).map(person=><option key={person.id} value={person.id}>{person.name} · {person.role}</option>)}</select></label>
   {kind!=='TEAM'&&<label className="policy-field">Tenggat tugas<input required className="config-input" type={kind==='FOLLOW_UP'?'date':'datetime-local'} value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label>}
   <label className="policy-field">Mulai penugasan<input required type="datetime-local" className="config-input" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label>
   {kind!=='TEAM'&&<label className="policy-field">Akhir delegasi (opsional)<input type="datetime-local" className="config-input" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/><small>Kosong berarti pengalihan permanen pada waktu mulai.</small></label>}
  </fieldset><label className="policy-field">Alasan penugasan / tindakan jadwal<textarea required minLength={5} maxLength={1000} className="config-input" value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></label>
  <button className="config-button" disabled={busy||!task} type="submit">Simpan jadwal penugasan</button></form>
  <p className="policy-note">Daftar menampilkan hingga 100 tugas terbuka dan 100 jadwal terbaru. Pilihan petugas diperiksa kembali terhadap scope, tahap, izin dan status akun saat jadwal disimpan/dijalankan.</p>
  <div className="grid gap-3">{rows.map(row=><article className="rounded-xl border border-border-glass p-4 space-y-2" key={row.id}><strong>{row.label}</strong><p>{ASSIGNMENT_STATES[row.state]||row.state} · {stamp(row.startsAt)} → {stamp(row.endsAt)}</p><p>{row.reason}</p>{row.lastError&&<p role="alert" className="app-error">{row.lastError}</p>}{row.state==='SCHEDULED'&&<button type="button" className="config-button" disabled={busy} onClick={()=>change(row,false)}>Batalkan jadwal</button>}{['FAILED','NEEDS_ATTENTION'].includes(row.state)&&<button type="button" className="config-button" disabled={busy} onClick={()=>change(row,true)}>Periksa ulang setelah diperbaiki</button>}</article>)}</div>
 </div></details>;
}
