import React,{useState,useEffect,useCallback} from 'react';
import {configApi} from '../../services/api';
export function NotificationDeliveryPanel(){
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState('');
 const load=useCallback(async()=>{setBusy(true);try{const res=await configApi.notificationDelivery();setData(res.data);setError('');}catch(e){setError(e.message);}finally{setBusy(false);}},[]);
 useEffect(()=>{let active=true;configApi.notificationDelivery().then(res=>{if(active)setData(res.data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 const retry=async id=>{setBusy(true);setError('');try{await configApi.retryNotificationDelivery({id,reason});setReason('');await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <section className="policy-panel policy-panel-body"><div className="policy-panel-heading"><div><h2>Pemantauan siaran notifikasi</h2><p>Data seluruh perusahaan yang sudah tersimpan, terpisah dari draf profil di atas.</p></div><button className="config-button" disabled={busy} onClick={load}>Perbarui status</button></div><p className="policy-note">Antrean hanya dibaca setelah transaksi berhasil. Siaran bukan bukti diterima atau dibaca; kotak masuk tetap menjadi sumber pesan. Pesan lama sebelum penerapan antrean tidak disiarkan ulang.</p>{error&&<p role="alert" className="policy-error">{error}</p>}{data?<><dl className="policy-delivery-metrics">{[['PENDING','Menunggu'],['RETRY','Menunggu ulang'],['FAILED','Gagal'],['SENT','Disiarkan'],['SKIPPED','Dilewati sesuai aturan']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{data.counts[key]||0}</dd></div>)}</dl><p className="policy-note">Diperiksa {new Date(data.checkedAt).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB{data.oldest&&` · Antrean tertua ${new Date(data.oldest.createdAt).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB`}.</p>{data.failed.length>0&&<div className="policy-delivery-failures"><label className="policy-field">Alasan mengulang antrean gagal<input className="config-input" minLength={5} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></label><p className="policy-note">Hingga 20 kegagalan terbaru. Mengulang tetap memeriksa aturan penerima yang efektif; tidak membuat pesan kotak masuk baru.</p><ul>{data.failed.map(row=><li key={row.id}><div><strong>{row.notification.title}</strong><p>{row.notification.type} · {row.attempts} percobaan</p></div><button className="config-button" disabled={busy||reason.trim().length<5} onClick={()=>retry(row.id)}>Antrekan ulang</button></li>)}</ul></div>}</>:<p className="policy-note">Memuat status antrean…</p>}</section>;
}
