import React,{useState} from 'react';
import {configApi} from '../../services/api';
import {POLICY_ROLES,BUSINESS_FEATURES,POLICY_OPTION_LABELS} from '../../../../shared/operational-policy.mjs';
const names={ADMIN:'Admin',SUPERVISOR:'Supervisor',SALES:'Sales',KEPALA_GUDANG:'Kepala gudang',SUPIR:'Driver'};
export function PolicySimulator({editor}){
 const [role,setRole]=useState(editor.scope.startsWith('ROLE:')?editor.scope.slice(5):'SALES'),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const simulate=async()=>{setBusy(true);setError('');try{const res=await configApi.simulate({scope:editor.scope,revision:editor.data.profile.revision,role});setResult(res.data);}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <section className="policy-panel policy-simulator"><header><h2>Simulasikan alur</h2><p>Lihat hasil gabungan aturan perusahaan, role, dan tim tanpa membuat transaksi.</p></header><div className="policy-panel-body"><div className="policy-simulate-controls"><label className="policy-field">Role<select className="config-input" value={role} onChange={e=>{setRole(e.target.value);setResult(null);}}>{POLICY_ROLES.map(r=><option key={r} value={r}>{names[r]}</option>)}</select></label><button className="config-button" disabled={busy||editor.busy||editor.dirty} onClick={simulate}>{busy?'Memeriksa…':'Simulasikan draf tersimpan'}</button></div>{editor.dirty&&<p>Simpan perubahan lokal agar dapat disimulasikan.</p>}{error&&<p role="alert" className="policy-error">{error}</p>}{result&&<><ol className="policy-flow">{result.steps.map((step,i)=><li key={i}><span>{i+1}</span>{step}</li>)}</ol>{result.conflicts.map(c=><p className="policy-error" key={c}>{c}</p>)}<details><summary>Ketersediaan seluruh fitur</summary><div className="policy-change-list">{result.features.map(f=><div key={f.key}><span>{BUSINESS_FEATURES.find(b=>b.key===f.key)?.label}</span><strong>{POLICY_OPTION_LABELS[f.mode]}</strong></div>)}</div></details><p className="policy-note">{result.note}</p></>}</div></section>;
}
