import React,{useState} from 'react';
import {point} from '../../OutletManagement/outletPresentation';
import {GoogleOutletMap} from './GoogleOutletMap';
import {knownPoint} from '../../../../../shared/outlet-validation.mjs';
import {comparisonDistance} from './outletComparisonMap';
export function GoogleOutletEvidence({run,outlet,fieldPoints=[],onRecheck,onSelect,disabled}){
 const cacheAvailable=run?.providerExpiresAt&&+new Date(run.providerExpiresAt)>Date.now();
 const candidates=cacheAvailable?run?.providerContent?.candidates||[]:[],[selected,setSelected]=useState('');
 const candidate=candidates.find(c=>c.placeId===(selected||run?.result?.selectedPlaceId))||candidates[0];
 const previous=run?.snapshot||outlet.nativeLocation||outlet;
 const recommendedId=Object.hasOwn(run?.result||{},'recommendedPlaceId')?run.result.recommendedPlaceId:run?.result?.selectedPlaceId;
 const recommended=candidates.find(c=>c.placeId===recommendedId);
 const distance=comparisonDistance(previous,recommended),selectedDistance=comparisonDistance(previous,candidate);
 const mapsLink=c=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(c.name||`${c.latitude},${c.longitude}`)}&query_place_id=${encodeURIComponent(c.placeId)}`;
 return <section className="ov-section ov-comparison"><div className="ov-section-heading"><div><h3>Peta dan perbandingan Google</h3><p className="ov-muted">Rekomendasi terkuat dari hasil pencarian yang tersedia. Tinjau identitas dan perbedaannya sebelum menyimpan keputusan.</p></div><span>{candidates.length} kandidat ditemukan</span></div>
  <div className="ov-comparison-summary"><div><span className="ov-tag">M · Titik sebelumnya</span><h4>{previous.name||outlet.name}</h4><p>{previous.address||'Alamat belum tersedia'}</p><p>{point(previous)}</p><small>{knownPoint(previous)?'Master yang menjadi dasar pemeriksaan':'Koordinat lama kosong; tidak dibuat titik pengganti'}</small>{knownPoint(previous)&&<a href={`https://www.google.com/maps/search/?api=1&query=${previous.latitude},${previous.longitude}`} target="_blank" rel="noreferrer">Buka titik sebelumnya</a>}</div><div><span className="ov-tag">G · Rekomendasi terkuat</span><h4>{recommended?.name||(recommended?'Deskripsi perlu diperbarui':'Belum ada rekomendasi yang layak')}</h4><p>{recommended?.address||'Periksa Google untuk memuat nama dan alamat kandidat.'}</p><p>{recommended?point(recommended):'Titik Google belum tersedia'}</p>{distance!=null&&<strong>{distance.toLocaleString('id-ID')} m dari titik sebelumnya · garis lurus</strong>}{recommended&&<a href={mapsLink(recommended)} target="_blank" rel="noreferrer">Buka rekomendasi Google</a>}</div></div>
  <GoogleOutletMap outlet={previous} candidate={candidate} recommended={recommended||null} fieldPoints={fieldPoints}/>
  {!candidates.length&&<p className="ov-notice">Belum ada kandidat Google yang dapat ditampilkan. Jalankan pemeriksaan untuk mencari atau memperbarui kandidat.</p>}
  {!!candidates.length&&<><h4>Tinjau kandidat</h4><div className="ov-candidates">{candidates.map((c,i)=><button type="button" className={`ov-candidate ${candidate?.placeId===c.placeId?'is-selected':''}`} key={c.placeId} disabled={disabled} onClick={()=>{setSelected(c.placeId);onSelect?.(c.placeId);}} aria-pressed={candidate?.placeId===c.placeId}><strong>{i+1}. {c.name||'Deskripsi perlu diperbarui'}</strong>{c.placeId===recommended?.placeId&&<span className="ov-tag">Rekomendasi terkuat</span>}<span>{c.address||'Jalankan ulang untuk memuat deskripsi Google.'}</span><small>Nama {c.nameScore??'—'}% · alamat {c.addressScore??'—'}% · {c.detailsConfirmed?'Detail diperiksa':'Detail belum terkonfirmasi'}</small>{[...(c.conflicts||[]),...(c.hardConflicts||[])].map(s=><small key={s} className="app-error">{s}</small>)}</button>)}</div></>}
  {candidate&&<><div className="ov-table-wrap"><table className="ov-table"><caption>Perbandingan kandidat yang sedang ditinjau{selectedDistance!=null?` · ${selectedDistance.toLocaleString('id-ID')} m dari titik sebelumnya`:''}</caption><thead><tr><th>Data</th><th>Master sebelumnya</th><th>Kandidat Google</th></tr></thead><tbody><tr><th>Nama</th><td>{previous.name}</td><td>{candidate.name||'Perbarui pemeriksaan'}</td></tr><tr><th>Alamat</th><td>{previous.address||'Belum tersedia'}</td><td>{candidate.address||'Perbarui pemeriksaan'}</td></tr><tr><th>Koordinat</th><td>{point(previous)}</td><td>{point(candidate)} · referensi Google</td></tr><tr><th>Status usaha</th><td>{outlet.deletedAt?'Nonaktif':'Aktif'}</td><td>{candidate.businessStatus||'Deskripsi perlu diperbarui'}</td></tr></tbody></table></div><div className="ov-attribution"><img src="https://developers.google.com/static/maps/documentation/images/google_on_white.png" alt="Google" width="62" height="20"/><a href={mapsLink(candidate)} target="_blank" rel="noreferrer">Buka kandidat di Google Maps ↗</a>{candidate.attributions?.map((a,i)=><span key={i}>{a.provider}</span>)}</div>{onRecheck&&<button type="button" className="app-button" disabled={disabled} onClick={()=>onRecheck(candidate.placeId)}>Periksa ulang kandidat ini</button>}{candidate.placeId!==run?.result?.selectedPlaceId&&<p className="ov-notice">Kandidat ini hanya sedang ditampilkan. Klik “Periksa ulang kandidat ini” sebelum menggunakannya sebagai dasar keputusan.</p>}</>}
  <p className="ov-muted">Kandidat Google merupakan referensi. Pilihan pada peta tidak langsung mengubah master atau menyetujui outlet.</p>
 </section>;
}
