import {ProposalActions} from './ProposalActions';
import React from 'react';
import {useApp} from '../../../context/AppContext';
import {useFormDraft} from '../../../shared/hooks/useFormDraft';
import {useUnsavedNavigation} from '../../../shared/hooks/useUnsavedNavigation';
export function OutletCorrectionProposal({review:r,disabled,act,digital}){
 const {user}=useApp(),o=r.outlet,p=r.proposal;
 const draft=useFormDraft(`outlet-proposal:${r.id}`,{name:o.name,address:o.address||'',latitude:o.latitude??'',longitude:o.longitude??'',reference:'',reason:''}),d=draft.value;
 useUnsavedNavigation(draft.dirty,disabled);
 const field=(key,value)=>draft.field(key)(value);
 const submit=e=>{e.preventDefault();const changes=Object.fromEntries(['name','address'].filter(k=>d[k]!==o[k]).map(k=>[k,d[k]]));if(d.latitude!==''&&d.longitude!==''&&(Number(d.latitude)!==o.latitude||Number(d.longitude)!==o.longitude)){changes.latitude=Number(d.latitude);changes.longitude=Number(d.longitude);}act(async()=>{await digital('PROPOSE',{changes,reference:d.reference,reason:d.reason,updatedAt:o.updatedAt});draft.clear();draft.setValue({name:o.name,address:o.address||'',latitude:o.latitude??'',longitude:o.longitude??'',reference:'',reason:''});});};
 return <section className="ov-section"><h3>Usulan koreksi master</h3>{p&&<div className="ov-proposal"><strong>{p.status==='PENDING'?'Menunggu persetujuan':p.status==='APPLIED'?'Sudah diterapkan':'Dikembalikan'}</strong><dl>{Object.entries(p.changes).map(([k,v])=><div key={k}><dt>{{name:'Nama',address:'Alamat',latitude:'Latitude',longitude:'Longitude'}[k]}</dt><dd>{p.status==='PENDING'?`${String(o[k]??'Kosong')} → `:''}{String(v)}</dd></div>)}</dl><p>{p.reference}</p>{p.status==='PENDING'&&user?.permissions?.can_apply_outlet_review&&<ProposalActions key={p.at} scope={r.id} disabled={disabled} act={act} digital={digital}/>}</div>}
 {user?.permissions?.can_propose_outlet_review&&<details><summary>{p?.status==='PENDING'?'Ganti usulan dengan referensi terbaru':'Ajukan perubahan berdasarkan bukti internal'}</summary><form className="app-form" onSubmit={submit}><p className="ov-muted">Isi sumber internal yang mengonfirmasi data, misalnya dokumen pelanggan atau konfirmasi langsung. Google tetap ditampilkan sebagai referensi penyedia.</p><div className="ov-form-grid">{[['name','Nama'],['address','Alamat'],['latitude','Latitude'],['longitude','Longitude']].map(([k,label])=><label className="app-field" key={k}>{label}<input value={d[k]} onChange={e=>field(k,e.target.value)} disabled={disabled} required={k==='name'||k==='address'} type={['latitude','longitude'].includes(k)?'number':'text'} step="any" min={k==='latitude'?-90:k==='longitude'?-180:undefined} max={k==='latitude'?90:k==='longitude'?180:undefined}/></label>)}</div><label className="app-field">Referensi bukti<textarea required minLength={10} maxLength={2000} value={d.reference} disabled={disabled} onChange={e=>field('reference',e.target.value)}/></label><label className="app-field">Alasan koreksi<textarea required minLength={10} maxLength={2000} value={d.reason} disabled={disabled} onChange={e=>field('reason',e.target.value)}/></label>{draft.storageError&&<p role="alert" className="app-error">{draft.storageError}</p>}<button className="app-button" disabled={disabled||(d.latitude==='')!==(d.longitude==='')}>Ajukan usulan</button></form></details>}
 </section>;
}
