import React, { useEffect, useState } from 'react';
import { NativeDialog } from '../../../shared/components/common/NativeDialog';
import { outletValidationApi } from '../../../services/api';
const SIGNALS = {reverseGeocode:'Alamat di titik GPS',forwardGeocode:'Titik berdasarkan alamat',findPlace:'Profil toko',nearbySearch:'Tempat di sekitar titik'};
export function OutletValidationDetail({outlet,onClose,onSaved}) {
  const [form,setForm] = useState({latitude:'',longitude:'',reason:''});
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState('');
  useEffect(()=>{if(outlet){setForm({latitude:String(outlet.latitude),longitude:String(outlet.longitude),reason:''});setError('');}},[outlet]);
  const save = async e=>{e.preventDefault();setBusy(true);setError('');try{await outletValidationApi.correctCoordinates(outlet.id,{latitude:Number(form.latitude),longitude:Number(form.longitude),reason:form.reason,updatedAt:outlet.updatedAt});await onSaved();onClose();}catch(err){setError(err.message);}finally{setBusy(false);}};
  const locate = ()=>{if(!navigator.geolocation){setError('GPS tidak tersedia pada perangkat ini.');return;}setBusy(true);navigator.geolocation.getCurrentPosition(pos=>{setForm(f=>({...f,latitude:String(pos.coords.latitude),longitude:String(pos.coords.longitude)}));setBusy(false);},err=>{setError(err.message);setBusy(false);},{enableHighAccuracy:true,timeout:15000,maximumAge:0});};
  return <NativeDialog open={Boolean(outlet)} title={outlet?.name || 'Detail outlet'} busy={busy} onClose={onClose}>{outlet && <div className="app-form"><p>{outlet.address || 'Alamat belum tersedia'}</p>{outlet.validationDetails?.note && <p className="app-notice">{outlet.validationDetails.note}</p>}<a className="app-link" href={`https://www.google.com/maps/search/?api=1&query=${outlet.latitude},${outlet.longitude}`} target="_blank" rel="noopener noreferrer">Buka koordinat pada peta</a><div className="workspace-card-grid">{Object.entries(outlet.validationDetails?.signals || {}).map(([key,s])=><article className="workspace-card" key={key}><h3>{SIGNALS[key] || key}</h3><p>{s.skipped?'Tidak diperiksa':`Skor: ${s.score ?? 0}%`}</p>{s.formattedAddress && <p>{s.formattedAddress}</p>}{s.distanceMeters != null && <p>Selisih titik: {Math.round(s.distanceMeters)} meter</p>}</article>)}</div>{(outlet.validationDetails?.warnings || []).map((w,i)=><p className="app-notice" key={i}>{w}</p>)}
    <form onSubmit={save} className="app-form"><h3>Koreksi GPS</h3><p>Gunakan lokasi perangkat hanya saat berada di outlet. Setelah koreksi, status kembali belum diperiksa.</p>{error && <p role="alert" className="app-error">{error}</p>}
    {outlet.googleSuggestedLat != null && outlet.googleSuggestedLng != null && <button type="button" className="app-button" disabled={busy} onClick={()=>setForm(f=>({...f,latitude:String(outlet.googleSuggestedLat),longitude:String(outlet.googleSuggestedLng)}))}>Isi kandidat koordinat untuk ditinjau</button>}
    <button type="button" className="app-button" onClick={locate} disabled={busy}>Ambil lokasi perangkat saat ini</button><div className="app-filter-grid"><label className="app-field">Lintang<input required type="number" step="any" min={-90} max={90} value={form.latitude} onChange={e=>setForm(f=>({...f,latitude:e.target.value}))}/></label><label className="app-field">Bujur<input required type="number" step="any" min={-180} max={180} value={form.longitude} onChange={e=>setForm(f=>({...f,longitude:e.target.value}))}/></label></div><label className="app-field">Alasan dan bukti pengecekan<textarea required minLength={10} maxLength={1000} value={form.reason} onChange={e=>setForm(f=>({...f,reason:e.target.value}))}/></label><button className="app-button app-button-primary" disabled={busy}>{busy?'Memproses…':'Simpan koreksi GPS'}</button></form>
    {(outlet.validationDetails?.coordinateHistory || []).length>0 && <details><summary>Riwayat koreksi GPS</summary>{outlet.validationDetails.coordinateHistory.map((h,i)=><p key={i}>{new Date(h.at).toLocaleString('id-ID')} — {h.reason}</p>)}</details>}
  </div>}</NativeDialog>;
}
