import React,{useCallback,useEffect,useState} from 'react';
import {outletValidationApi} from '../../../services/api';
import {stamp} from '../../OutletManagement/outletPresentation';
const labels={QUEUED:'Antre',RUNNING:'Sedang diperiksa',STOPPING:'Menunggu outlet berjalan selesai',PAUSED:'Dijeda',DONE:'Selesai'};
export function OutletValidationJobs({onOpen}){
 const [jobs,setJobs]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const load=useCallback(async()=>{try{const r=await outletValidationApi.jobs();setJobs(r.data);setError('');}catch(e){setError(e.message);}},[]);
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer);},[load]);
 const act=async(id,action)=>{setBusy(id);try{await outletValidationApi.jobAction(id,{action,reason:action==='STOP'?'Dijeda oleh pengguna dari antrean':'Dilanjutkan oleh pengguna dari antrean'});await load();}catch(e){setError(e.message);}finally{setBusy('');}};
 return <section className="ov-section"><div className="ov-section-heading"><div><h2>Pemeriksaan massal saya</h2><p className="ov-muted">Kemajuan disimpan di server. Halaman boleh ditutup; diperbarui setiap 15 detik.</p></div><button type="button" className="app-button" onClick={load}>Perbarui batch</button></div>{error&&<p role="alert" className="app-error">{error}</p>}{!jobs.length&&<p className="ov-muted">Belum ada batch. Aktifkan pemeriksaan Google saat memilih beberapa outlet.</p>}{jobs.map(j=><details className="ov-job" key={j.id}><summary>{labels[j.status]} · {j.items.filter(i=>i.state==='DONE').length}/{j.items.length} berhasil · {j.items.filter(i=>i.state==='FAILED').length} gagal <small>{stamp(j.createdAt)}</small></summary><p>{j.reason}</p><div className="app-actions">{['QUEUED','RUNNING'].includes(j.status)&&<button type="button" className="app-button" disabled={busy===j.id} onClick={()=>act(j.id,'STOP')}>Jeda setelah outlet berjalan</button>}{j.status==='PAUSED'&&<button type="button" className="app-button" disabled={busy===j.id} onClick={()=>act(j.id,'RESUME')}>Lanjutkan</button>}{['DONE','PAUSED'].includes(j.status)&&j.items.some(i=>i.state==='FAILED'&&i.attempts<3)&&<button type="button" className="app-button" disabled={busy===j.id} onClick={()=>act(j.id,'RETRY')}>Ulangi gagal (maks. 3 percobaan)</button>}</div><ul className="ov-job-items">{j.items.map(i=><li key={i.outletId}><span>{i.state==='DONE'?'Berhasil':i.state==='FAILED'?'Gagal':i.state==='RUNNING'?'Memeriksa':'Menunggu'} · {i.error||i.code||i.outletId}</span>{i.reviewId&&<button type="button" className="app-button" onClick={()=>onOpen(i.reviewId)}>Lihat kasus</button>}</li>)}</ul></details>)}</section>;
}
