import {FieldTaskReview} from './FieldTaskReview';
import React from 'react';
import {useApp} from '../../../context/AppContext';
import {outletValidationApi} from '../../../services/api';
import {useFormDraft} from '../../../shared/hooks/useFormDraft';
export function OutletFieldReview({review:r,disabled,act,readOnly=false}){
 const {user,settings}=useApp(),draft=useFormDraft(`outlet-field-assignment:${r.id}`,{owner:'',reviewer:'',instructions:'',due:'',manualCode:''}),{owner,reviewer,instructions,due,manualCode}=draft.value;
 const setOwner=draft.field('owner'),setReviewer=draft.field('reviewer'),setInstructions=draft.field('instructions'),setDue=draft.field('due');
 const active=r.fieldTasks?.find(t=>['OPEN','SUBMITTED'].includes(t.status));
 const assign=e=>{e.preventDefault();act(()=>outletValidationApi.assignField(r.outletId,r.id,{revision:r.revision,ownerId:owner,reviewerId:reviewer,instructions,...(manualCode?{manualPjpCode:manualCode}:{}),...(due?{dueAt:new Date(due).toISOString()}:{})}));};
 return <section className="ov-section"><h3>Pemeriksaan lapangan</h3><p className="ov-muted">Tugaskan bila Google dan bukti internal belum memadai. Tugas masuk PJP Sales hari ini tanpa membuat presensi. Mode agenda mengikuti parameter tim Sales saat penugasan.</p>{r.fieldTasks?.map(t=><FieldTaskReview key={t.id} task={t} actors={r.fieldActors} disabled={disabled} readOnly={readOnly} act={act}/>)}
 {!readOnly&&user?.permissions?.can_assign_outlet_review&&active?.status!=='SUBMITTED'&&<details><summary>{active?'Jadwalkan ulang / alihkan tugas':'Tugaskan Sales'}</summary><form className="app-form" onSubmit={assign}><div className="ov-form-grid"><label className="app-field">Sales pelaksana<select required disabled={disabled} value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Pilih Sales</option>{r.fieldActors?.sales.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="app-field">Pemeriksa hasil<select required disabled={disabled} value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">Pilih SPV / Admin</option>{r.fieldActors?.reviewers.filter(p=>p.id!==owner).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><label className="app-field">Pertanyaan / tujuan pemeriksaan<textarea required minLength={10} maxLength={2000} value={instructions} onChange={e=>setInstructions(e.target.value)} disabled={disabled}/></label><label className="app-field">Tenggat (opsional)<input type="datetime-local" value={due} disabled={disabled} onChange={e=>setDue(e.target.value)}/><small>Kosong memakai SLA {settings.OUTLET_FIELD_SLA_HOURS??48} jam sesuai kalender.</small></label><label className="app-field">Kode PJP manual (bila diperlukan)<input maxLength={128} value={manualCode} disabled={disabled} onChange={e=>draft.field('manualCode')(e.target.value)}/><small>Hanya diperlukan bila belum ada PJP hari ini dan penomoran PJP diatur manual. Untuk mode sampai selesai, siapkan PJP berkode manual pada setiap hari berikutnya.</small></label><button className="app-button" disabled={disabled||settings.OUTLET_FIELD_ENABLED===false}>Simpan penugasan</button>{settings.OUTLET_FIELD_ENABLED===false&&<p className="ov-muted">Tugas baru dinonaktifkan Admin.</p>}</form></details>}
 </section>;
}
