import React from 'react';
export function OutletReviewDecisionForm({review,user,decision,setDecision,draft,busy,onSubmit,readiness,adminReadiness,acknowledged,setAcknowledged}){
 const d=draft.value,adminMode=decision==='ADMIN_DIGITAL_KEEP',run=review.runs[0];
 const selected=run?.providerContent?.candidates?.find(c=>c.placeId===run?.result?.selectedPlaceId);
 return <form className="ov-section app-form" onSubmit={onSubmit}>
  <h3>Selesaikan pemeriksaan</h3>
  {user.role==='ADMIN'&&<div className="ov-admin-review"><h4>Pertimbangan khusus Admin</h4><p>{adminReadiness.available?'Aktif. Anda dapat menerima kandidat yang belum memenuhi syarat standar setelah meninjau peta dan perbedaannya.':'Tidak tersedia. Periksa izin keputusan dan parameter pertimbangan Admin.'}</p><p className="ov-muted">Batas Admin: nama minimal {adminReadiness.policy.OUTLET_REVIEW_ADMIN_NAME_PERCENT}% atau alamat minimal {adminReadiness.policy.OUTLET_REVIEW_ADMIN_ADDRESS_PERCENT}%, atau telepon cocok. Kandidat ambigu {adminReadiness.policy.OUTLET_REVIEW_ADMIN_ALLOW_AMBIGUOUS?'diizinkan':'tidak diizinkan'}; konflik data {adminReadiness.policy.OUTLET_REVIEW_ADMIN_ALLOW_CONFLICTS?'diizinkan dengan alasan':'tidak diizinkan'}.</p>{adminReadiness.available&&!adminReadiness.canConfirm&&<ul>{adminReadiness.issues.map(i=><li key={i.code}>{i.message} {i.action}</li>)}</ul>}{adminReadiness.available&&decision!=='ADMIN_DIGITAL_KEEP'&&<button type="button" className="app-button" disabled={busy||!adminReadiness.canConfirm} onClick={()=>setDecision('ADMIN_DIGITAL_KEEP')}>Gunakan pertimbangan Admin</button>}<p className="ov-muted">Atur melalui Parameter → Outlet &amp; registrasi → Validasi outlet · pertimbangan Admin.</p></div>}
  <label className="app-field">Dasar keputusan<select value={decision} disabled={busy} onChange={e=>setDecision(e.target.value)}><option value="DIGITAL_KEEP" disabled={!readiness.canConfirm}>Konfirmasi Google sesuai syarat standar</option>{user.role==='ADMIN'&&<option value="ADMIN_DIGITAL_KEEP" disabled={!adminReadiness.canConfirm}>Konfirmasi dengan pertimbangan Admin</option>}<option value="FIELD_KEEP" disabled={!review.fieldTasks?.some(t=>t.status==='DONE')}>Hasil lapangan yang telah diterima</option><option value="INTERNAL_KEEP">Bukti internal yang dapat ditelusuri</option><option value="CANCEL">Tutup tanpa verifikasi</option></select></label>
  {['DIGITAL_KEEP','ADMIN_DIGITAL_KEEP'].includes(decision)&&<><p><strong>Kandidat dasar keputusan:</strong> {selected?.name||run?.result?.selectedPlaceId||'Belum tersedia'}</p><p className="ov-muted">Titik Google digunakan untuk rute/radius bila diaktifkan pada parameter. Titik master sebelumnya tetap tercatat; GPS lapangan terpercaya tetap diprioritaskan.</p></>}
  {adminMode&&<div className="ov-admin-ack"><strong>Perbedaan yang Anda terima</strong><ul>{adminReadiness.warnings.map((warning,i)=><li key={i}>{warning}</li>)}</ul><label><input type="checkbox" checked={acknowledged} disabled={busy} onChange={e=>setAcknowledged(e.target.checked)} required/><span>Saya telah meninjau titik sebelumnya, kandidat Google, serta perbedaan data dan memilih kandidat ini berdasarkan alasan di bawah.</span></label><p className="ov-muted">Skor asli tetap disimpan. Pembaruan lokasi berikutnya memerlukan tinjauan Admin baru.</p></div>}
  <label className="app-field">{adminMode?'Alasan Admin menerima kandidat ini':'Alasan keputusan'}<textarea value={d.reason} onChange={e=>draft.field('reason')(e.target.value)} required minLength={adminMode?20:10} maxLength={2000} disabled={busy} placeholder={adminMode?'Jelaskan informasi yang menguatkan pilihan meskipun terdapat perbedaan.':undefined}/></label>
  {decision==='INTERNAL_KEEP'&&<label className="app-field">Referensi dokumen / konfirmasi internal<textarea value={d.reference} onChange={e=>draft.field('reference')(e.target.value)} required minLength={10} maxLength={2000} disabled={busy}/></label>}
  {draft.storageError&&<p role="alert" className="app-error">{draft.storageError}</p>}
  <button className="app-button app-button-primary" disabled={busy||decision==='DIGITAL_KEEP'&&!readiness.canConfirm||adminMode&&(!adminReadiness.canConfirm||!acknowledged)}>{busy?'Menyimpan…':'Simpan keputusan & tutup kasus'}</button>
 </form>;
}
