import React,{useState} from 'react';
import {NativeDialog} from '../../../shared/components/common/NativeDialog';
import {useOutletDirectory} from '../../OutletManagement/useOutletDirectory';
import {OutletReviewRequest} from '../../OutletManagement/OutletReviewRequest';
export function ValidationOutletPicker({onClose,onSaved}) {
 const d=useOutletDirectory('reviewPick'),[selected,setSelected]=useState([]),[next,setNext]=useState(false);
 const toggle=o=>setSelected(p=>p.some(x=>x.id===o.id)?p.filter(x=>x.id!==o.id):p.length<30?[...p,o]:p);
 if(next)return <OutletReviewRequest outlets={selected} onClose={()=>setNext(false)} onSaved={onSaved}/>;
 return <NativeDialog open title="Pilih outlet untuk pemeriksaan opsional" onClose={onClose} className="outlet-dialog"><div className="app-form"><p className="outlet-muted">Pilih maksimal 30 outlet. Outlet yang tidak dipilih tidak akan diproses.</p><label className="app-field">Cari outlet<input type="search" value={d.search} onChange={e=>d.setSearch(e.target.value)} placeholder="Nama, kode, alamat"/></label>{d.error&&<p className="app-error" role="alert">{d.error}</p>}<div className="outlet-picker-list">{d.data.filter(o=>!o.deletedAt).map(o=><label key={o.id} className="outlet-picker-row"><input type="checkbox" checked={selected.some(s=>s.id===o.id)} disabled={selected.length>=30&&!selected.some(s=>s.id===o.id)} onChange={()=>toggle(o)}/><span><strong>{o.name}</strong><small>{o.outletCode} · {o.cluster?.name}</small><small>{o.address}</small></span></label>)}{d.loading&&<p role="status">Memuat outlet…</p>}{!d.loading&&!d.data.length&&<p>Tidak ada outlet sesuai pencarian.</p>}</div><div className="outlet-pagination"><button type="button" className="app-button" disabled={d.page<=1||d.loading} onClick={()=>d.setPage(d.page-1)}>Sebelumnya</button><span>{d.page} / {d.pagination.totalPages}</span><button type="button" className="app-button" disabled={d.page>=d.pagination.totalPages||d.loading} onClick={()=>d.setPage(d.page+1)}>Berikutnya</button></div><footer className="outlet-form-footer"><span>{selected.length} outlet dipilih</span><button type="button" className="app-button app-button-primary" disabled={!selected.length} onClick={()=>setNext(true)}>Lanjut · alasan pemeriksaan</button></footer></div></NativeDialog>;
}
