import {unitDescription} from '../../../../../shared/product-units.mjs';
import {canOrderOperation} from '../../../../../shared/order-operation-permissions.mjs';
import React,{useState,useEffect} from 'react';
import {deliveryApi,ordersApi,collectPages} from '../../../services/api';
import {useApp} from '../../../context/AppContext';
import {TAB_IDS} from '../../../constants/navigation';
import {OrderRemainderAction} from './OrderRemainderAction';
import {orderStatusLabel,fulfillmentLabel} from '../../Sales/salesPresentation';
export function OrderFulfillmentPanel({orders:provided,onSelect,onChanged,renderActions}){
  const {user,setActiveTab}=useApp();const [orders,setOrders]=useState(provided||[]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [loading,setLoading]=useState(!provided),[query,setQuery]=useState(''),[status,setStatus]=useState('ALL'),[page,setPage]=useState(1);
  const refresh=async()=>{setLoading(true);try{const r=await collectPages(ordersApi.getAllOrders);setOrders(r.data);setError('');}catch(e){setError(e.message);}finally{setLoading(false);}};
  useEffect(()=>{if(provided)setOrders(provided);else refresh();},[provided]);
  const [dates,setDates]=useState({}),[notes,setNotes]=useState({});
  const filtered=orders.filter(o=>`${o.code||o.id} ${o.customerSnapshot?.name||o.pjpStop?.outlet?.name||''}`.toLowerCase().includes(query.toLowerCase())&&(status==='ALL'?o.status!=='REJECTED'&&!['FULFILLED','CLOSED_WITH_CANCELLATION'].includes(o.fulfillmentStatus):status==='HISTORY'?['FULFILLED','CLOSED_WITH_CANCELLATION'].includes(o.fulfillmentStatus):status==='REJECTED'?o.status==='REJECTED':(status==='LATE'?o.status!=='REJECTED'&&!['FULFILLED','CLOSED_WITH_CANCELLATION'].includes(o.fulfillmentStatus)&&o.promisedAt&&new Date(o.promisedAt)<new Date():status==='PENDING_APPROVAL'?o.status===status:o.fulfillmentStatus===status)));
  const pages=Math.max(1,Math.ceil(filtered.length/20)),current=Math.min(page,pages),visible=filtered.slice((current-1)*20,current*20);
  const save=async(e,o)=>{e.preventDefault();setBusy(true);try{await deliveryApi.setOrderPromise(o.id,{promisedAt:new Date(`${dates[o.id]}:00+07:00`).toISOString(),note:notes[o.id]});if(onChanged)await onChanged();else await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <section className="space-y-3"><h2 className="text-lg font-bold">Pemenuhan order</h2><p className="text-sm">Persetujuan dan pemenuhan dipantau terpisah. Jumlah diterima berdasarkan hasil pengiriman pelanggan; tidak terkait saldo stok.</p>{!provided&&<button disabled={loading} className="min-h-11 border rounded-xl px-3" onClick={refresh}>Perbarui order</button>}{error&&<p role="alert" className="text-red-600">{error}</p>}
    <div className="flex flex-wrap gap-3"><label>Cari order / pelanggan<input type="search" className="form-input block" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label>Status pemenuhan<select className="form-input block" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="ALL">Semua order terbuka</option>{!provided&&<option value="REJECTED">Order ditolak</option>}<option value="PENDING_APPROVAL">Menunggu keputusan</option>{!provided&&<option value="HISTORY">Riwayat terpenuhi / dibatalkan</option>}<option value="PARTIAL">Diterima sebagian</option><option value="LATE">Lewat janji kirim</option></select></label></div>
    {visible.map(o=><details key={o.id} className="border rounded-xl bg-surface p-4"><summary className="cursor-pointer min-h-11"><strong>{o.code||o.id.slice(0,8)} · {o.customerSnapshot?.name||o.pjpStop?.outlet?.name}</strong><span className="block text-sm">{orderStatusLabel(o.status)} · {fulfillmentLabel(o.fulfillmentStatus)} · Dibuat {new Date(o.createdAt).toLocaleDateString('id-ID')} · Janji kirim: {o.promisedAt?new Date(o.promisedAt).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'}):'Belum ditetapkan'}</span></summary>
      {o.status!=='REJECTED'&&<div className="overflow-x-auto"><table className="w-full text-sm my-3"><thead><tr>{['Barang','Dipesan','Dalam packing','Diterima','Dibatalkan','Sisa kewajiban','Belum dipacking'].map(t=><th className="p-2 text-left" key={t}>{t}</th>)}</tr></thead><tbody>{o.fulfillmentLines.map(i=><tr key={i.id} className="border-t"><td className="p-2">{i.product?.name}<span className="block text-xs">{unitDescription(i)}</span></td>{[i.quantity,i.prepared,i.accepted,i.cancelled||0,i.remaining,i.unpacked].map((v,n)=><td key={n} className="p-2">{v}</td>)}</tr>)}</tbody></table></div>}
      {o.rejectionReason&&<p className="text-red-600">Alasan penolakan: {o.rejectionReason}</p>}
      {user.role==='ADMIN'&&<OrderRemainderAction order={o} onChanged={onChanged||refresh}/>}
      {!!o.history?.length&&<details><summary className="cursor-pointer min-h-11">Riwayat order</summary>{o.history.map((h,n)=><p className="text-sm py-1" key={n}>{new Date(h.at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} · {h.action} · {h.actorName||h.actorId} · {h.note}{h.lines?` · ${h.lines.map(i=>`${i.id.slice(0,8)}: ${i.quantity}`).join(', ')}`:''}</p>)}</details>}
      {user.role==='ADMIN'&&o.status!=='REJECTED'&&!['FULFILLED','CLOSED_WITH_CANCELLATION'].includes(o.fulfillmentStatus)&&<div className="space-y-3">{o.status==='PENDING_APPROVAL'?user.permissions?.can_approve_order!==false&&<button className="min-h-11 border rounded-xl px-3" onClick={()=>setActiveTab(TAB_IDS.ADMIN_APPROVAL)}>Verifikasi / setujui order</button>:user.permissions?.can_manage_packing_list!==false&&o.fulfillmentLines.some(i=>i.unpacked>0)&&<button className="min-h-11 border rounded-xl px-3" onClick={()=>onSelect?onSelect(o):setActiveTab(TAB_IDS.DELIVERY_PACKING_LIST)}>Susun packing sisa order</button>}
        {canOrderOperation(user,'PROMISE')&&<form onSubmit={e=>save(e,o)} className="space-y-2"><label className="block">Janji pengiriman WIB<input required type="datetime-local" className="form-input block w-full" value={dates[o.id]||''} onChange={e=>setDates({...dates,[o.id]:e.target.value})}/></label><label className="block">Catatan konfirmasi pelanggan<input required maxLength={2000} className="form-input block w-full" value={notes[o.id]||''} onChange={e=>setNotes({...notes,[o.id]:e.target.value})}/></label><button disabled={busy} className="min-h-11 border rounded-xl px-3">Simpan janji kirim</button></form>}</div>}
      {renderActions?.(o)}
    </details>)}{loading&&<p role="status">Memuat order…</p>}{!loading&&!error&&!filtered.length&&<p>{orders.length?'Tidak ada order sesuai filter.':'Tidak ada order terbuka.'}</p>}
    {filtered.length>0&&<nav aria-label="Halaman order" className="flex items-center gap-3"><button className="min-h-11 border rounded-xl px-3" disabled={current===1} onClick={()=>setPage(current-1)}>Sebelumnya</button><span>{filtered.length} order · Halaman {current}/{pages}</span><button className="min-h-11 border rounded-xl px-3" disabled={current===pages} onClick={()=>setPage(current+1)}>Berikutnya</button></nav>}
  </section>;
}
