import React,{useState} from 'react';
import {deliveryApi} from '../../../services/api';
const stages={PICK:'Penyiapan barang',CHECK:'Pemeriksaan barang',LOAD:'Loading / serah terima'};
const stamp=v=>new Date(v).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'});
export function PreparationTasks({route,people,onChanged,canManage}){
  const [stage,setStage]=useState('PICK'),[owner,setOwner]=useState(''),[due,setDue]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const assign=async e=>{e.preventDefault();setBusy(true);setError('');try{await deliveryApi.routeAction(route.id,{action:'ASSIGN_PREPARATION',stage,ownerId:owner,dueAt:new Date(`${due}:00+07:00`).toISOString(),note});await onChanged();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <section className="space-y-3"><h3 className="font-bold">Tugas persiapan gudang</h3>{Object.entries(stages).map(([key,label])=>{const done=route.preparation?.[key],task=route.preparation?.tasks?.[key];return <p key={key} className="text-sm"><strong>{label}</strong> · {done?`Selesai oleh ${done.actorName||done.actorId} · ${stamp(done.at)}`:task?`${task.ownerName} · Tenggat ${stamp(task.dueAt)}${new Date(task.dueAt)<new Date()?' · Terlambat':''}`:'Belum ditugaskan'}</p>;})}
    {canManage&&route.status==='DRAFT'&&!route.cancelledAt&&!route.closedAt&&<details><summary className="min-h-11 cursor-pointer">Tugaskan / ganti PIC persiapan</summary><form onSubmit={assign} className="space-y-3 border rounded-xl p-3"><fieldset disabled={busy} className="space-y-3"><label className="block">Tahap<select className="form-input block w-full" value={stage} onChange={e=>setStage(e.target.value)}>{Object.entries(stages).map(([key,label])=><option disabled={!!route.preparation?.[key]} value={key} key={key}>{label}</option>)}</select></label><label className="block">Petugas gudang<select required className="form-input block w-full" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Pilih petugas</option>{people.filter(p=>['ADMIN','KEPALA_GUDANG'].includes(p.role)).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label className="block">Tenggat persiapan WIB<input required type="datetime-local" className="form-input block w-full" value={due} onChange={e=>setDue(e.target.value)}/></label><label className="block">Instruksi / alasan penugasan<textarea required maxLength={2000} className="form-input block w-full" value={note} onChange={e=>setNote(e.target.value)}/></label><button className="min-h-11 border rounded-xl px-3">{busy?'Menyimpan…':'Simpan penugasan'}</button></fieldset>{error&&<p role="alert" className="text-red-600">{error}</p>}</form></details>}
  </section>;
}
