import React,{useState,useEffect,useCallback,useRef} from 'react';
import {LuRefreshCw,LuSearch} from 'react-icons/lu';
import {vehiclesApi} from '../../../services/api';
import {useWorkspaceState} from '../../../shared/hooks/useWorkspaceState';
import {VehicleMaintenanceCard} from './VehicleMaintenanceCard';
import {VehicleConditionControl} from './VehicleConditionControl';
import {RecordMaintenanceModal} from './RecordMaintenanceModal';
import {VehicleServicePolicyEditor} from './VehicleServicePolicyEditor';
import {VehicleServiceHistory} from './VehicleServiceHistory';
import {useApp} from '../../../context/AppContext';
const condition={AVAILABLE:'Layak digunakan',IN_SERVICE:'Dalam perawatan',BROKEN:'Tidak layak',READY:'Siap digunakan'};
export function VehicleMaintenanceDashboard({embedded=false}){
 const {user}=useApp();
 const [vehicles,setVehicles]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[record,setRecord]=useState(null);
 const [selectedId,select]=useWorkspaceState('warehouseVehicle',''),flight=useRef(0);
 const refresh=useCallback(async()=>{const version=++flight.current;setLoading(true);try{const res=await vehiclesApi.getAll();if(version===flight.current){setVehicles(res.data||[]);setError('');}}catch(e){if(version===flight.current)setError(e.message);}finally{if(version===flight.current)setLoading(false);}},[]);
 useEffect(()=>{refresh();return()=>{flight.current++;};},[refresh]);
 const visible=vehicles.filter(v=>`${v.code} ${v.name}`.toLocaleLowerCase('id-ID').includes(search.trim().toLocaleLowerCase('id-ID'))),selected=visible.find(v=>v.id===selectedId)||visible[0];
 return <div className={embedded?'logistics-workspace':'workspace-page logistics-workspace'}><header className="admin-page-heading"><div>{!embedded&&<p className="admin-eyebrow">Gudang / Armada</p>}{embedded?<h2>Kendaraan & servis</h2>:<h1>Kendaraan & servis</h1>}<p>Periksa kondisi kendaraan, kapasitas, dan servis sebelum menetapkan trip.</p></div><button type="button" disabled={loading} className="admin-button" onClick={()=>{if(window.dispatchEvent(new CustomEvent('app:before-navigate',{cancelable:true})))refresh();}}><LuRefreshCw/>Perbarui</button></header>{error&&<p role="alert" className="admin-feedback error">{error} Data terakhir tetap ditampilkan; perbarui sebelum mengubah kondisi.</p>}<div className="admin-toolbar"><label className="admin-search"><LuSearch/><input type="search" aria-label="Cari kendaraan" placeholder="Cari kode atau nama kendaraan…" value={search} onChange={e=>setSearch(e.target.value)}/></label><span className="admin-footnote">{vehicles.length} kendaraan terdaftar</span></div><div className="logistics-split"><section className="admin-panel logistics-stop-list"><div className="admin-panel-heading"><h2>Armada</h2></div><ul>{visible.map(v=><li key={v.id}><button type="button" aria-pressed={selected?.id===v.id} onClick={()=>{if(window.dispatchEvent(new CustomEvent('app:before-navigate',{cancelable:true})))select(v.id);}}><span><strong>{v.code} · {v.name}</strong><small>{condition[v.condition]||v.condition||'Kondisi belum tersedia'}</small><small>{Number(v.totalKm||0).toLocaleString('id-ID')} km · {v.maxCartons} karton</small></span></button></li>)}</ul>{!visible.length&&<p className="admin-empty">{loading?'Memuat armada…':'Tidak ada kendaraan sesuai pencarian.'}</p>}</section>{selected&&<fieldset disabled={!!error} className="logistics-vehicle-detail"><VehicleMaintenanceCard vehicle={selected} onRecord={()=>setRecord(selected)}/><section className="admin-panel logistics-action-panel"><VehicleConditionControl key={`${selected.id}:${selected.updatedAt}`} vehicle={selected} onChanged={refresh}/></section>{user?.role==='ADMIN'&&<VehicleServicePolicyEditor key={`${selected.id}:${selected.updatedAt}`} vehicle={selected} onChanged={refresh}/>}<VehicleServiceHistory vehicle={selected}/></fieldset>}</div>{record&&<RecordMaintenanceModal vehicle={record} onClose={()=>setRecord(null)} onSuccess={()=>{setRecord(null);refresh();}}/>}</div>;
}
