import React,{useState} from 'react';
import {LuRefreshCw,LuSearch,LuTruck,LuPrinter,LuArrowLeft} from 'react-icons/lu';
import {useApp} from '../../../context/AppContext';
import {TAB_IDS} from '../../../constants/navigation';
import {useWorkspaceState} from '../../../shared/hooks/useWorkspaceState';
import {PackingListPrintModal} from './PackingListPrintModal';
import {InvoiceReconciliationPanel} from './InvoiceReconciliationPanel';
export function WarehousePackingWorkspaceView({error,loading,page,printDoc,refresh,result,search,setPage,setPrintDoc,setSearch,status,setStatus}){
 const {setActiveTab,user}=useApp(),[scope,setScope]=useState('remaining'),[selectedId,select]=useWorkspaceState('warehousePacking','');
 const visible=(result.items||[]).filter(p=>scope==='all'||Number(p.remainingCartons??p.totalCartons)>0);
 const selected=(result.items||[]).find(p=>p.id===selectedId);
 return <div className="workspace-page logistics-workspace"><header className="admin-page-heading"><div><p className="admin-eyebrow">Gudang / Dokumen muatan</p><h1>{selected?selected.code:'Antrean packing'}</h1><p>Dokumen dilepas Admin untuk dialokasikan ke trip. Sisa muatan dihitung dari dokumen dan pengiriman.</p></div>{selected?<button type="button" className="admin-button" onClick={()=>select('')}><LuArrowLeft/>Daftar dokumen</button>:<button type="button" className="admin-button" disabled={loading} onClick={refresh}><LuRefreshCw/>Perbarui</button>}</header>
  {error&&<p role="alert" className="admin-feedback error">{error} Perbarui data sebelum merencanakan alokasi.</p>}
  {selected?<section className="admin-panel logistics-document"><div className="admin-panel-heading"><div><h2>{selected.outlet?.name||'Outlet belum tersedia'}</h2><p>{selected.outlet?.address}</p></div><span className="admin-status">{selected.status==='RELEASED'?'Dilepas ke gudang':selected.status}</span></div><div className="logistics-metrics">{[['Total karton',selected.totalCartons||0],['Dialokasikan',selected.allocatedCartons||0],['Sisa alokasi',selected.remainingCartons??selected.totalCartons??0]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="admin-table-scroll"><table className="admin-data-table"><caption>Rincian barang pada dokumen</caption><thead><tr><th>Produk / SKU</th><th>Jumlah dokumen</th><th>Sisa alokasi</th></tr></thead><tbody>{(selected.remainingItems||selected.items||[]).map((item,index)=><tr key={item.lineId||index}><td><strong>{item.name}</strong><span className="block admin-footnote">{item.sku||'Tanpa SKU'}</span></td><td>{item.quantity} {item.unit||'unit'}</td><td>{item.remaining??item.quantity} {item.unit||'unit'}</td></tr>)}</tbody></table></div><section><h3>Faktur terlampir</h3>{selected.invoices?.length?selected.invoices.map(i=><p key={i.id}>{i.invoiceNumber} · {i.totalCartons} karton</p>):<p className="admin-footnote">Belum ada faktur terlampir.</p>}</section>{selected.notes&&<section><h3>Catatan Admin</h3><p>{selected.notes}</p></section>}<div className="admin-heading-actions"><button type="button" className="admin-button" onClick={()=>setPrintDoc(selected)}><LuPrinter/>Lihat / cetak dokumen</button>{user.permissions?.can_manage_delivery_routes!==false&&<button type="button" className="admin-button primary" disabled={!!error} onClick={()=>setActiveTab(TAB_IDS.DELIVERY_ROUTES)}><LuTruck/>Rencanakan alokasi trip</button>}</div><details><summary>Pemeriksaan faktur dan penerimaan</summary><InvoiceReconciliationPanel packing={selected} admin={false} onChanged={refresh}/></details>{selected.history?.length>0&&<details><summary>Riwayat dokumen</summary>{selected.history.map((h,i)=><p key={i}>{h.action} · {h.at?new Date(h.at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'}):'Waktu belum tercatat'}</p>)}</details>}</section>:<>
   <div className="admin-toolbar"><label className="admin-search"><LuSearch/><input type="search" aria-label="Cari packing list" value={search} placeholder="Cari kode dokumen atau outlet…" onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label className="admin-select-label">Dokumen pada halaman<select value={scope} onChange={e=>setScope(e.target.value)}><option value="remaining">Masih memiliki sisa alokasi</option><option value="all">Semua hasil pencarian</option></select></label>{status&&<button type="button" className="admin-button" onClick={()=>{setStatus('');setPage(1);}}>Hapus filter status</button>}</div>
   <section className="admin-panel"><div className="admin-panel-heading"><h2>Dokumen dari Admin</h2><span>{result.total||0} hasil pencarian</span></div><div className="admin-table-scroll"><table className="admin-data-table"><caption className="sr-only">Antrean dokumen packing yang dapat dialokasikan</caption><thead><tr><th>Dokumen / outlet</th><th>Dilepas</th><th>Total karton</th><th>Sisa karton</th><th>Alokasi trip</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><button type="button" className="admin-table-link" onClick={()=>select(p.id)}><strong>{p.code}</strong><span>{p.outlet?.name||'Outlet belum tersedia'}</span></button></td><td>{p.releasedAt?new Date(p.releasedAt).toLocaleDateString('id-ID',{timeZone:'Asia/Jakarta'}):'Belum tercatat'}</td><td>{p.totalCartons||0}</td><td><strong>{p.remainingCartons??p.totalCartons??0}</strong></td><td>{p.deliveryStops?.length?`${p.deliveryStops.length} alokasi`:'Belum dialokasikan'}</td></tr>)}</tbody></table></div>{!visible.length&&<div className="admin-empty"><h2>{loading?'Memuat dokumen…':'Tidak ada dokumen dalam pilihan ini'}</h2><p>Ubah pencarian atau lingkup. Jika belum ada dokumen dilepas, minta Admin memeriksa packing list.</p></div>}<footer className="admin-pagination"><span>Halaman {page} / {Math.max(1,Math.ceil((result.total||0)/20))} · Sisa alokasi difilter pada halaman ini</span><div><button type="button" disabled={page===1||loading} onClick={()=>setPage(page-1)}>Sebelumnya</button><button type="button" disabled={page*20>=result.total||loading} onClick={()=>setPage(page+1)}>Berikutnya</button></div></footer></section>
  </>}
  <PackingListPrintModal document={printDoc} onClose={()=>setPrintDoc(null)}/>
 </div>;
}
