import React,{useState} from 'react';
import {useApp} from '../../../../context/AppContext';
import {TAB_IDS} from '../../../../constants/navigation';
export function ClusterWorkspace({management:m,onEdit,onOutlets}){
 const {user,setActiveTab}=useApp(),[query,setQuery]=useState(''),[selected,setSelected]=useState('');
 const canManage=['ADMIN','SUPERVISOR'].includes(user.role)&&user.permissions?.can_manage_clusters!==false;
 const visible=m.masterClusters.filter(c=>`${c.name} ${c.code} ${c.region} ${c.assignedSpvName} ${c.assignedSalesName}`.toLowerCase().includes(query.toLowerCase())),current=visible.find(c=>c.id===selected)||visible[0];
 return <section className="cluster-workspace"><div className="planner-intro"><div><h2>Wilayah dan penanggung jawab</h2><p>Kelompokkan outlet berdasarkan wilayah dan jenis perdagangan. Jadwal kunjungan disusun melalui Planner.</p></div>{canManage&&<div className="app-actions"><button type="button" className="admin-button" onClick={()=>m.setIsImportModalOpen(true)}>Impor outlet</button><button type="button" className="admin-button primary" onClick={()=>setActiveTab(TAB_IDS.CREATE_CLUSTER)}>Buat cluster</button></div>}</div>
  <div className="planner-metrics"><div><span>Cluster terdaftar</span><strong>{m.masterClusters.filter(c=>c.name!=='Belum Ditugaskan').length}</strong></div><div><span>Outlet dalam wilayah</span><strong>{m.stats.totalAllocated}/{m.stats.totalOutlets}</strong></div><div><span>Cluster perlu penanggung jawab</span><strong>{m.masterClusters.filter(c=>c.name!=='Belum Ditugaskan'&&(!c.supervisorId||!c.assignedSalesId)).length}</strong></div></div>
  {m.error&&<p role="alert" className="admin-feedback error">{m.error}<button className="admin-button" onClick={m.reload}>Muat ulang</button></p>}
  <div className="cluster-workspace-columns"><section className="admin-panel"><div className="planner-panel-body"><label className="app-field">Cari wilayah<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cluster, Sales, atau Supervisor"/></label></div><div className="cluster-directory">{visible.map(c=><button type="button" key={c.id} aria-pressed={current?.id===c.id} onClick={()=>setSelected(c.id)}><strong>{c.name}</strong><span>{c.region} · {c.allocatedOutletsCount} outlet</span><small>{c.assignedSalesName} · {c.assignedSpvName}</small>{(!c.assignedSalesId||!c.supervisorId)&&c.name!=='Belum Ditugaskan'&&<em>Penugasan belum lengkap</em>}</button>)}{m.loading&&<p role="status" className="app-empty">Memuat wilayah…</p>}{!m.loading&&!visible.length&&<p className="app-empty">{query?'Tidak ada wilayah sesuai pencarian.':'Belum ada wilayah. Buat cluster pertama untuk mengelompokkan outlet.'}</p>}</div></section>
   <section className="admin-panel planner-panel-body">{current?<><div className="planner-status-line"><h2>{current.name}</h2><span>{current.code}</span></div><dl className="cluster-summary"><dt>Region</dt><dd>{current.region}</dd><dt>Jenis perdagangan</dt><dd>{current.tradeType==='GENERAL_TRADE'?'General Trade':current.tradeType==='MODERN_TRADE'?'Modern Trade':current.tradeType==='MIXED'?'Campuran · perlu diperbaiki':'Belum ada outlet'}</dd><dt>Supervisor</dt><dd>{current.assignedSpvName}</dd><dt>Sales penanggung jawab</dt><dd>{current.assignedSalesName}</dd><dt>Anggota outlet</dt><dd>{current.allocatedOutletsCount}</dd></dl><p>Penugasan wilayah menentukan tanggung jawab pelanggan. Tanggal, interval, dan urutan kunjungan ditetapkan dalam Planner.</p>{canManage&&<fieldset disabled={!!m.error||m.loading||!!m.deletingId}><div className="app-actions"><button className="admin-button" onClick={()=>onOutlets(current)}>Kelola anggota outlet</button><button className="admin-button" disabled={current.name==='Belum Ditugaskan'} onClick={()=>onEdit(current)}>Edit penanggung jawab</button><button className="admin-button" disabled={current.name==='Belum Ditugaskan'||current.allocatedOutletsCount>0||!!current.assignedSalesId} onClick={()=>{if(window.confirm(`Hapus cluster kosong ${current.name}?`))m.handleDeleteCluster(current.id);}}>Hapus cluster kosong</button></div></fieldset>}</>:<p className="app-empty">Pilih wilayah untuk melihat rincian dan penugasannya.</p>}</section>
  </div>
 </section>;
}
