import {useFeaturePolicy} from '../../../../shared/hooks/useFeaturePolicy';
import React,{useState} from 'react';
import {OutletListPanel} from './OutletListPanel';
import {RouteReferenceCard} from './RouteReferenceCard';
import {BusinessCodeInput} from '../../../../shared/components/common/BusinessCodeInput';
import {ClusterImpactReview} from './ClusterImpactReview';
const steps=['Tim & wilayah','Pilih outlet','Urutan referensi','Tinjau & simpan'];
export function ClusterControlPanel({builder:b,user,allOutlets,dataLoading,dataError,onRetry,onCancel}){
  const featurePolicy=useFeaturePolicy('CLUSTERS');
 const [query,setQuery]=useState(''),pool=[...new Map([...allOutlets,...b.selectedOutlets].map(o=>[o.id,o])).values()],selectedIds=b.selectedOutlets.map(o=>o.id),disabled=b.busy||b.saving||!featurePolicy.canStart;
 const candidates=pool.filter(o=>o.type===b.draft.tradeType&&(o.cluster?.supervisorId===b.draft.supervisorId||o.cluster?.name==='Belum Ditugaskan'||selectedIds.includes(o.id))).filter(o=>`${o.name} ${o.outletCode||''} ${o.address||''}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="cluster-control-panel" aria-label="Buat cluster"><header className="cluster-panel-header"><h1>Buat cluster wilayah</h1><p>Langkah {b.step} dari 4 · {steps[b.step-1]}</p><ol className="cluster-steps" aria-label="Tahap pembuatan">{steps.map((label,i)=><li key={label} aria-current={b.step===i+1?'step':undefined}><span>{i+1}</span>{label}</li>)}</ol></header><div className="cluster-panel-body app-form">
  {!featurePolicy.canStart&&<p role="status" className="app-notice">{featurePolicy.reason}</p>}{b.error&&<p role="alert" className="app-error">{b.error}</p>}{(b.restored||b.policyChanged)&&<p className="app-notice">{b.restoreMessage} Anggota dan dampaknya diperiksa kembali sebelum penyimpanan.</p>}{b.storageError&&<p role="alert" className="app-error">{b.storageError}</p>}{dataError&&<p role="alert" className="app-error">{dataError}<button className="app-button" onClick={onRetry}>Muat ulang outlet</button></p>}
  <fieldset disabled={disabled} className="app-form">{b.step===1&&<><p>Pilih tim dan tanggung jawab wilayah terlebih dahulu. Cluster dapat memiliki banyak outlet; jadwal kunjungannya disusun pada Planner.</p>{b.teamError&&<p role="alert" className="app-error">{b.teamError}<button type="button" onClick={b.loadTeam}>Muat ulang tim</button></p>}{user.role==='ADMIN'?<label className="app-field">Tim Supervisor<select value={b.draft.supervisorId} onChange={e=>b.field('supervisorId',e.target.value)} disabled={b.teamLoading||!!selectedIds.length}><option value="">Pilih tim</option>{b.team.supervisors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>:<p>Tim: <strong>{user.name}</strong></p>}<label className="app-field">Sales penanggung jawab<select value={b.draft.assignedSalesId} onChange={e=>b.field('assignedSalesId',e.target.value)} disabled={!b.draft.supervisorId||b.teamLoading}><option value="">Belum ditugaskan</option>{b.team.sales.filter(s=>s.supervisorId===b.draft.supervisorId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><BusinessCodeInput entity="CLUSTER" value={b.draft.code||''} onChange={v=>b.field('code',v)} disabled={disabled}/><label className="app-field">Nama cluster<input maxLength={150} value={b.draft.name} onChange={e=>b.field('name',e.target.value)}/></label><label className="app-field">Region / wilayah<input maxLength={100} value={b.draft.region} onChange={e=>b.field('region',e.target.value)}/></label><label className="app-field">Jenis perdagangan<select value={b.draft.tradeType} disabled={!!selectedIds.length} onChange={e=>b.field('tradeType',e.target.value)}><option value="GENERAL_TRADE">General Trade</option><option value="MODERN_TRADE">Modern Trade</option></select></label><label className="app-field">Warna penanda<input type="color" value={b.draft.colorHex} onChange={e=>b.field('colorHex',e.target.value)}/></label>{selectedIds.length>0&&<p className="admin-footnote">Lepaskan pilihan outlet pada langkah berikutnya untuk mengganti tim atau jenis.</p>}</>}
  {b.step===2&&<><p>Klik marker untuk menambah atau melepas satu outlet. Klik area peta untuk menetapkan pusat saran; pilihan Anda tetap tersimpan.</p><label className="app-field">Cari outlet<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>{dataLoading&&<p role="status">Memuat outlet…</p>}<OutletListPanel outlets={candidates} selectedIds={selectedIds} disabled={disabled} onToggle={id=>b.toggleOutlet(pool.find(o=>o.id===id))}/><strong>{selectedIds.length} outlet dipilih</strong><details><summary className="cluster-suggestion-title">Saran outlet terdekat</summary><div className="app-form"><label className="app-field">Jumlah saran<input type="number" min="1" max="100" value={b.outletCount} onChange={e=>b.setOutletCount(Number(e.target.value))}/></label><button type="button" className="app-button" onClick={b.suggest} disabled={!b.centerPoint||disabled}>Cari dari titik pusat</button>{!b.centerPoint&&<p>Pilih titik pusat pada area peta terlebih dahulu.</p>}{b.suggestions.length>0&&<><p>{b.suggestions.length} outlet disarankan: {b.suggestions.map(o=>o.name).join(', ')}</p><button type="button" className="app-button" onClick={b.applySuggestions}>Tambahkan saran ke pilihan</button></>}</div></details></>}
  {b.step===3&&<><h2>Urutan referensi wilayah</h2><p>Opsional. Gunakan sebagai referensi geografis; tanggal dan urutan pelaksanaan tetap disusun dalam Planner.</p><button type="button" className="app-button" disabled={!selectedIds.length||disabled} onClick={b.generate}>{b.busy?'Menghitung…':'Hitung rekomendasi urutan'}</button>{b.routes.map((r,i)=><RouteReferenceCard key={i} route={r} index={i} isActive={i===b.activeRouteIndex} onClick={()=>b.setActiveRouteIndex(i)} outlets={pool}/>)}<p className="admin-footnote">Jarak adalah estimasi antartitik. Garis mengikuti jalan jika layanan rute tersedia.</p></>}
  {b.step===4&&<><h2>{b.draft.name}</h2><dl className="cluster-summary"><dt>Region</dt><dd>{b.draft.region}</dd><dt>Tim</dt><dd>{b.team.supervisors.find(s=>s.id===b.draft.supervisorId)?.name||user.name}</dd><dt>Sales</dt><dd>{b.team.sales.find(s=>s.id===b.draft.assignedSalesId)?.name||'Belum ditugaskan'}</dd><dt>Anggota</dt><dd>{selectedIds.length} outlet</dd></dl><ClusterImpactReview review={b.review}/>{!b.review&&<button type="button" className="app-button" onClick={b.next}>Periksa ulang dampak</button>}<p>Setelah wilayah disimpan, susun rencana tanggal kunjungan melalui Planner.</p></>}
  </fieldset></div><footer className="cluster-panel-footer"><button type="button" className="app-button" disabled={b.busy||b.saving} onClick={b.step===1?onCancel:()=>b.setStep(v=>v-1)}>{b.step===1?'Kembali ke wilayah':'Kembali'}</button>{b.step<4?<button type="button" className="app-button app-button-primary" disabled={disabled||b.teamLoading||!!b.teamError} onClick={b.next}>Lanjut</button>:<button type="button" className="app-button app-button-primary" disabled={disabled||!b.review} onClick={b.save}>{b.saving?'Menyimpan…':'Simpan wilayah'}</button>}</footer></section>;
}
