import React,{useState,useRef} from 'react';
import {GuardedDialog} from '../../../../shared/components/common/GuardedDialog';
import {clustersApi} from '../../../../services/api';
import {parseSpreadsheetCsv,generateCsvTemplateContent} from '../../../../services/spreadsheetImportService';
import {SpreadsheetPreviewTable} from './SpreadsheetPreviewTable';
export function SpreadsheetImportModal({isOpen,onClose,onImportSuccess}){
 const [text,setText]=useState(''),[rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(null),[name,setName]=useState('');
 const flight=useRef(false),readVersion=useRef(0);
 const close=()=>{readVersion.current++;setText('');setRows([]);setError('');setReview(null);setName('');onClose();};
 const read=async e=>{const file=e.target.files?.[0];if(!file)return;const version=++readVersion.current;setBusy(true);setReview(null);setError('');try{if(file.size>3*1024*1024)throw new Error('CSV maksimal 3 MB.');const content=await file.text();if(version!==readVersion.current)return;const parsed=parseSpreadsheetCsv(content);if(parsed.length>1000)throw new Error('Maksimal 1.000 baris per impor.');setRows(parsed);setText(content);setName(file.name);}catch(err){setRows([]);setText('');setError(err.message);}finally{if(version===readVersion.current)setBusy(false);}};
 const download=()=>{const url=URL.createObjectURL(new Blob([generateCsvTemplateContent()],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='Template_Wilayah_Outlet.csv';link.click();URL.revokeObjectURL(url);};
 const submit=async()=>{if(flight.current)return;flight.current=true;setBusy(true);setError('');try{if(!review){setReview((await clustersApi.previewImport(rows)).data);return;}await onImportSuccess(text,review.token);close();}catch(e){setReview(null);setError(e.message);}finally{flight.current=false;setBusy(false);}};
 return <GuardedDialog className="planning-dialog" open={isOpen} title="Impor wilayah dan outlet" onClose={close} busy={busy} dirty={!!text} closeDescription="File dan pratinjau yang belum diterapkan akan dilepas. Data operasional belum berubah."><div className="app-form"><p>Impor memperbarui master outlet dan wilayah. Jadwal kunjungan diterbitkan melalui Planner setelah penugasan tim diperiksa.</p><button type="button" className="app-button" onClick={download} disabled={busy}>Unduh template CSV</button><label className="app-field">File CSV<input type="file" accept=".csv,text/csv" disabled={busy} onChange={read}/></label>{name&&<p>{name} · {rows.length} baris</p>}<p className="admin-footnote">F1/F2/F4 adalah interval setiap 1/2/4 minggu. Header dibaca berdasarkan nama kolom. Gunakan ClusterCode bila nama cluster tidak unik.</p>{error&&<p role="alert" className="app-error">{error}</p>}{rows.length>0&&<SpreadsheetPreviewTable previewRows={rows.slice(0,30)}/>}{rows.length>30&&<p>Pratinjau menampilkan 30 baris pertama; semua baris diperiksa oleh server.</p>}{review&&<section className="cluster-impact"><h3>Perubahan yang akan diterapkan</h3><p>{review.summary.created} outlet baru · {review.summary.updated} diperbarui · {review.summary.moved} pindah wilayah · {review.summary.coordinatesChanged} perubahan koordinat</p><ul>{review.changes.map(c=><li key={c.outletCode}><strong>{c.name} · {c.outletCode}</strong><span>{c.action==='CREATE'?'Tambah':'Perbarui'} · {c.from} → {c.to}{c.coordinatesChanged?' · koordinat berubah':''}</span></li>)}</ul><p>{review.impact.templateReferences} referensi template · {review.impact.draftPlans.length} draft perlu ditinjau · {review.impact.publishedPjps} PJP terbit terdampak</p>{!!review.impact.draftPlans.length&&<ul>{review.impact.draftPlans.map(p=><li key={p.id}>{p.name} · revisi {p.revision}</li>)}</ul>}<p>Rute referensi cluster terdampak akan dibersihkan. PJP yang sudah terbit tetap tersimpan; tinjau ulang draft yang memakai outlet berpindah.</p></section>}<button type="button" className="app-button app-button-primary" disabled={busy||!rows.length} onClick={submit}>{busy?'Memproses…':review?'Terapkan perubahan impor':'Periksa perubahan di server'}</button></div></GuardedDialog>;
}
